### ISSUE TITLE
The G3MiOSDemo can not be compiled in Xcode4.2, how can I solve the problem?

### ISSUE THREAD

**Issue by gdp12315** [glob3mobile/g3m#1]
The G3MiOSDemo can not be compiled in Xcode4.2,
  how can I solve the problem?
Thanks

**Comment by mdelacalle** [comment]
The compilation problem are about iOS, xCode platform, we are working on the latest xCode where we can compile to iOS prior versions. 
We haven't different versions for every development tool, and we can't give support about this problem, try in Apple developers or make concrete questions.
Thank you
