### ISSUE TITLE
'hello world'-like sample app displays nothing

### ISSUE THREAD

**Issue by akosmaroy** [glob3mobile/g3m#10]
Hi,

I'm trying to create a very basic sample app using g3m, by following the README documentation and the demo code - but I get 'nothing' for a display :( please find the following screenshot attached:

![screenshot](https://f.cloud.github.com/assets/333140/1704443/fd7f4e7e-60ca-11e3-996c-81d75bb6d71b.png)

the code I used is based on a generic 'Hello, World' app generated by eclipse, and then adding a few lines to add a G3MWidget_Android instance. here is my MainActivity.java:

```
package aero.schwa.av;

import org.glob3.mobile.specific.G3MBuilder_Android;
import org.glob3.mobile.specific.G3MWidget_Android;

import android.app.Activity;
import android.os.Bundle;
import android.view.Menu;
import android.widget.LinearLayout;

public class MainActivity extends Activity {

    private G3MWidget_Android _g3mWidget;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        final G3MBuilder_Android builder = new G3MBuilder_Android(this);
         _g3mWidget = builder.createWidget();

        final LinearLayout layout = (LinearLayout) findViewById(R.id.glob3);
        layout.addView(_g3mWidget);
    }

    @Override
    public boolean onCreateOptionsMenu(Menu menu) {
        // Inflate the menu; this adds items to the action bar if it is present.
        getMenuInflater().inflate(R.menu.main, menu);
        return true;
    }

}
```

and my layout file:

```
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:paddingBottom="@dimen/activity_vertical_margin"
    android:paddingLeft="@dimen/activity_horizontal_margin"
    android:paddingRight="@dimen/activity_horizontal_margin"
    android:paddingTop="@dimen/activity_vertical_margin"
    tools:context=".MainActivity" >

    <LinearLayout
           android:id="@+id/glob3"
           android:layout_width="fill_parent"
           android:layout_height="match_parent"
           android:orientation="horizontal" >

    </LinearLayout>

</RelativeLayout>
```

besides these, I didn't really anything in the Hello World project - other than adding a dependency on the G3M Android SDK.

what am I doing wrong?

the 'official' demo compiles & runs fine

Akos

**Comment by akosmaroy** [comment]
ok, I found the solution, I need to add the following to AndroidManifest.xml:

```
    <uses-feature android:glEsVersion="0x00020000" />

    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.INTERNET" />
```

maybe this could be added to the README file as well

**Comment by mdelacalle** [comment]
We are writing a Getting Started Document , Thanks for the feedback, we will try to include all the problems that a user can have when start the deployment.
If you have any suggestions or you want contribute to documentation you are welcome.
I hope have the document as soon as possible on the repository.

 Thanks.
