### ISSUE TITLE
rand() C++ to Java Problem

### ISSUE THREAD

**Issue by stefaniea** [glob3mobile/g3m#106]
using the rand() function in C++ does not get converted correctly to Java. Is there another function to get a random number that is known to work with the converter?

**Comment by DiegoGomezDeck** [comment]
The singleton IMathUtils::instance() is there to hide those differences between platforms.

In your case:
  /*\* answer a double value in the range 0.0 (inclusive) and 1.0 (exclusive) */
  virtual double nextRandomDouble() const = 0;

**Comment by stefaniea** [comment]
Great! Thank you!
