### ISSUE TITLE
suggestion: add access to G3MWidget's effects scheduler

### ISSUE THREAD

**Issue by akosmaroy** [glob3mobile/g3m#11]
I'm trying to create my own camera movement effect, which is based on the CameraGoToPositionEffect class. I'd like to use it the same way, but I can't add it to G3MWidget._effectsScheduler, as there is no accessor function for this member of G3MWidget.

is this by design?

if so, how would one create & regularly update his own effect scheduler (as done in the render() function of G3MWidget)?

of not, then I'd suggest adding a getter function to the EffectsScheduler instance, so that users of G3MWidget can add effects to it

**Comment by DiegoGomezDeck** [comment]
Thank you for your suggestion.

It was just a "conservative" design option (never expose your parts early ;)), but I think it's not a problem to create that accessor.

BTW, it's not better to expand the current CameraGoToPositionEffect class (for instance: adding roll) and overload the setAnimatedCameraPosition set of methods?

Let me know if you prefer going with the accessor solution.

**Comment by akosmaroy** [comment]
the current one could be extended as well

what I changed in my implementation is that I removed the code that 'looks down' at the middle of the animation, and also the code that raises the elevation of the camera.

and yes, I'd need roll as well, but for that, the Camera object itself needs a setRoll() method first

**Comment by DiegoGomezDeck** [comment]
To resume:

1) I will add the getEffectsScheduler() method on the widget. Is pays benefits by itself for a large set of posible cases.
2) I can expand the current CameraGoToPositionEffect with a new boolean parameter like "linearPitch" (similar to the current linearHeight).
3) Camera::setRoll(), yes I agree... we can do that, but it'll take some some time than the other 2 points. I'll let you know when can be done.

**Comment by DiegoGomezDeck** [comment]
getEffectsScheduler() already done in purgatory branch.
