### ISSUE TITLE
map scale

### ISSUE THREAD

**Issue by DimitrisMarm** [glob3mobile/g3m#111]
Hello there,

I try to add map scale in my app but i can't find any method that returns the scale or the camera's viewport to calc the map scale. So i want to ask if there any way to do this?

Thanks.

**Comment by DimitrisMarm** [comment]
Is the cameraPosition._height equals to mapScale?

**Comment by DiegoGomezDeck** [comment]
There are not a direct meaning of "scale" in 3d maps.  I mean: in a 3d view (think when the camera is looking to the horizon) you see different levels of tiles at the very same time.

cameraPosition._height is the height (in meters, from the ground) of the camera, it's not the scale.

**Comment by DimitrisMarm** [comment]
thanks  @DiegoGomezDeck.

So if  i use it as 2d map i have to calc the scale on my own. Right?

**Comment by DimitrisMarm** [comment]
Hi again,

I have another question, which is : 

i have a marker and i have put a textView beside of it with ICameraConstrainer. But when i zoom in/out or i move the camera it appears that the textView is sticked in  the same x,y pixels and not beside of the marker. Is there any way to put the textView beside of the marker while i move the camera or zooming in or out?

Thanks again.
