### ISSUE TITLE
Overlay point cloud data

### ISSUE THREAD

**Issue by WuhanMonkey** [glob3mobile/g3m#113]
Hello All,

I have the “Hello World" example working on my iPad and I am trying to write code to overlay point cloud data sets on the specific location showing on the Hello World demo. I saw there is a demo on android of this but not sure how to get started with iOS. 

Also, I am trying to find g3m iOS API description online but haven't figure it out. Anyone knows it? 

Thanks for any help and suggestions.

**Comment by DiegoGomezDeck** [comment]
Hi @WuhanMonkey 

Please take a look to the G3MApp sources, specifically G3MPointCloudDemoScene for a "small" cloud rendering, and G3MStreamingPointCloud1DemoScene/G3MStreamingPointCloud2DemoScene for the streaming solution.

Here https://www.youtube.com/watch?v=JtApdYXNOrA you can find a video where we presented the point-cloud streaming technology at the last FOSS4G-NA.
