### ISSUE TITLE
Overlay topographic maps layer from public WMS server

### ISSUE THREAD

**Issue by WuhanMonkey** [glob3mobile/g3m#118]
Hello all,

Just wondering anyone knows how to use the topographic layer (shaded relief) on the base of blueMarble layer? I am struggling to find an usable public WMS server that host topographic layer information. 

Or maybe I can use the elevation data provided by NASA, but I need to download the image from a url first. In the java API example, the function is: 

URL url = NasaBillElevationDataURL.compoundURL(sector, extent);

But I can't find related information about it in iOS SDK. How can I do that in iOS？

Beside that, I also tried to download the elevation file and use it directly. But from NASA elevation I can only download .hgt file. However, the sdk seems only support .bil file. How should I solve this problem?

Any help would be appreciated. Thanks

**Comment by DiegoGomezDeck** [comment]
Hi @WuhanMonkey 

For today, we only have support for terrain-elevation-models that fits on the device RAM.

The "streaming" of TEM is not working well just now.  It's a very wanted feature, but we didn't get the time/resources yet to make it works.
