### ISSUE TITLE
How to use the cache system for offline map in iOS

### ISSUE THREAD

**Issue by WuhanMonkey** [glob3mobile/g3m#122]
Checked https://github.com/glob3mobile/g3m/blob/purgatory/tools/precachingReadme.txt
But I didn't find the API in iOS to do the precaching.

**Comment by mdelacalle** [comment]
Hi
You can use the same file on iOS, so you create de cache with the android app and use it on iOS version

**Comment by WuhanMonkey** [comment]
@mdelacalle thanks for your quick reply, but I don't think I get your point.

What do you mean to use the "precachingReadme.txt" ? I thought it is an example in Android version for how to deploy the cache into disk. So did you mean, I need to write an Android app first to deploy the cache and use my iOS app to consume it? How can I do that? Does iOS app automatically consume it? More instruction would be really helpful.

Thanks
-Chengpeng

**Comment by mdelacalle** [comment]
Exactly
You can use this code to prepare your cache or use the same API to do the same thing on iOS. The idea is use the own g3m API to get the data.

**Comment by WuhanMonkey** [comment]
I can't find the corresponding API in iOS. @DiegoGomezDeck  Could you please give some instructions on that?

Thanks
