### ISSUE TITLE
Geopackage support for the latest specification

### ISSUE THREAD

**Issue by surf9** [glob3mobile/g3m#127]
Hi there

I'm just wondering if there will be support of the latest Geopackage specification in g3m on Android? Is it currently in development? If so, are you able to provide us a rough date when it will be ready?

Thank you for your help.

**Comment by DiegoGomezDeck** [comment]
Hi @surf9 

We don't have plans to implement Geopackage support in the near future.

BTW, if you need this feature please contact us and we can discuss about the option to promote it to the roadmap.

**Comment by surf9** [comment]
Thanks for letting me know.
