### ISSUE TITLE
catch 22: G3MWidget.initSingletons() and G3MBuilder setup

### ISSUE THREAD

**Issue by akosmaroy** [glob3mobile/g3m#13]
I bumped into a catch-22 like situation.

one has to set up G3MBuilder before creating a G3MWidget on Android, which might need some of the singletons created in G3MWidget.initSingletons() - for example, the StringBuilder, used by G3M's URL class. but these singletons are not initialized before G3MBuilder.createWidget() is called.

moreover, one can't postpone this setup to after .createWidget(), as the possibility is not there to change some of the aspects of the widget after build (for example the ElevationDataProvider cannot be changed afterwards)

I wonder what the proper solution to this problem is

**Comment by DiegoGomezDeck** [comment]
For initialization stuff (like the situation you're reporting) we have a mechanism names "InitializationTask" (see class GInitializationTask).   It's a task that it called just after all the framework is set up, and provides you a G3MContext with all the stuff you can need.

BTW, The elevation data provider _can_ be changed on the fly following the next steps:
- get a pointer to PlanetRenderer from the widget, using getPlanetRender().
- use  planetRenderer->setVerticalExaggeration()
- use planetRenderer->setElevationDataProvider()

**Comment by akosmaroy** [comment]
thanks for both pointers

as for the initialization task - how would I invoke it?

**Comment by DiegoGomezDeck** [comment]
builder.setInitializationTask(GInitializationTask initializationTask );

---

public abstract class GInitializationTask extends GTask
{
  public abstract void run(G3MContext context);  // <-- run your code here

  public abstract boolean isDone(G3MContext context);  // <-- answer true when your initialization gets done
}
