### ISSUE TITLE
How to download data using WFS?

### ISSUE THREAD

**Issue by octavianiLocator** [glob3mobile/g3m#139]
In my application, I am adding a custom map on the Earth using WMSLayer and this works nice and simple. I have some features to add to the rendering, which I initially do by using Marks.

How can I query features from my geoserver, such as interest points, polygons and polylines, using the Web Feature Service in g3m framework? Is there another way to do it?

EDIT: Can you please help @mdelacalle @DiegoGomezDeck @akosmaroy ?

**Comment by DiegoGomezDeck** [comment]
Hi @octavianiLocator 

We have not support for WFS right on the g3m core.

Anyway, you can use any external library to interact with a WFS server and create Marks, Shapes, etc based on the data you have.

**Comment by octavianiLocator** [comment]
Hi @DiegoGomezDeck 
Thank you for clarifying the topic for me. 
Have you tested any libraries with g3m for WFS? Recommendations? 

EDIT: For example, how is it better to obtain info about and represent roads/street info?
Also, I would like to use WFS for the data required to draw Marks as in #141.

**Comment by akosmaroy** [comment]
On 2015-09-27 11:24, octavianiLocator wrote:

> Hi @DiegoGomezDeck https://github.com/DiegoGomezDeck
> Thank you for clarifying the topic for me.
> Have you tested any libraries with g3m for WFS? Recommendations?

Diego, I see you CC'd me - although we did not interface with WFS 
sources at the end directly, only did some AIXM visualization, that did 
include some GML constructs
