### ISSUE TITLE
Specific BBOX for WMS Layer

### ISSUE THREAD

**Issue by NidhalSNSdev** [glob3mobile/g3m#14]
Hi,

How can i use Sector.fromDegrees() to speicify an BBOX for my Layer in Android Application.
My BBOX is:  -90 , -180, 90, 180

Thanks

**Comment by mdelacalle** [comment]
Hi,

This sector is:  Sector.fullSphere()

If you want to build one , here your have the code.

```
  final Geodetic2D lower = new Geodetic2D( //
           Angle.fromDegrees(40.1665739916489), //
           Angle.fromDegrees(-5.85449532145337));
  final Geodetic2D upper = new Geodetic2D( //
           Angle.fromDegrees(40.3320215899527), //
           Angle.fromDegrees(-5.5116079822178570));

  final Sector demSector = new Sector(lower, upper);
```

Thanks

**Comment by NidhalSNSdev** [comment]
But i have a problem: My Layer work only with BBOX=-90 , -180, 90, 180 and not for other BBOX and when i try tu watch in console i have this message:
Created 8 first level tiles
12-11 17:14:33.316: I/System.out(2929): &WIDTH=256&HEIGHT=256&BBOX=-90.0,-180.0,0.0,-90.0
12-11 17:14:33.336: I/System.out(2929): &WIDTH=256&HEIGHT=256&BBOX=-90.0,-90.0,0.0,0.0
12-11 17:14:33.376: I/System.out(2929): &WIDTH=256&HEIGHT=256&BBOX=-90.0,0.0,0.0,90.0
12-11 17:14:33.406: I/System.out(2929): &WIDTH=256&HEIGHT=256&BBOX=-90.0,90.0,0.0,180.0
12-11 17:14:33.426: I/System.out(2929): &WIDTH=256&HEIGHT=256&BBOX=0.0,-180.0,90.0,-90.0
12-11 17:14:33.466: I/System.out(2929): &WIDTH=256&HEIGHT=256&BBOX=0.0,-90.0,90.0,0.0
12-11 17:14:33.486: I/System.out(2929): &WIDTH=256&HEIGHT=256&BBOX=0.0,0.0,90.0,90.0
12-11 17:14:33.546: I/System.out(2929): &WIDTH=256&HEIGHT=256&BBOX=0.0,90.0,90.0,180.0

**Comment by mdelacalle** [comment]
Sorry
I’m not understand your problem.

is it a WMS Layer?
Please could you put here the layer definition??

thanks

**Comment by NidhalSNSdev** [comment]
final Geodetic2D lower = new Geodetic2D(Angle.fromDegrees(-90), Angle.fromDegrees(-180));
         final Geodetic2D upper = new Geodetic2D(Angle.fromDegrees(90), Angle.fromDegrees(180)); 
         final Sector demSector = new Sector(lower, upper);

```
    final WMSLayer precipitationLayer = new WMSLayer(
            "precipitation_amount_60mn", new URL(
                    "http://screamshot.makinacorpus.net/public/api/ogc/wms/radar/"
                            , false),
            WMSServerVersion.WMS_1_3_0, demSector, "image/png",
            "EPSG:4326", "", true, new LevelTileCondition(0, 18),
            TimeInterval.fromDays(30), true);
```

**Comment by mdelacalle** [comment]
I have tested your layer and the server response error 403: Method no implemented.
Please could you send me the get capabilities URL of you server
Thank you

**Comment by NidhalSNSdev** [comment]
Sorry,

To use this server you must add extra parametre for WMS Layer  :
token=27e26598e322422db64d9d40e8c9aaa2       this token is avalaible only for 4 hour.
Thanks

**Comment by mdelacalle** [comment]
Ok, but anyway, could you send me the getCapabilities sentence (Token included) or a successful request (on browser)

Thank you

**Comment by NidhalSNSdev** [comment]
with BBOX = -90.0,-180,90.0,180  it's OK :

http://screamshot.makina-corpus.net/public/api/ogc/wms/radar/?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&LAYERS=precipitation_amount_60mn&STYLES=&FORMAT=image/png&TRANSPARENT=true&HEIGHT=256&WIDTH=256&CRS=EPSG%3A4326&SRS=EPSG%3A4326&BBOX=-90.0,-180,90.0,180&token=27e26598e322422db64d9d40e8c9aaa2

But when i change BBOX for example to: 0,90,90,180 it's KO

http://screamshot.makina-corpus.net/public/api/ogc/wms/radar/?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&LAYERS=precipitation_amount_60mn&STYLES=&FORMAT=image/png&TRANSPARENT=true&HEIGHT=256&WIDTH=256&CRS=EPSG%3A4326&SRS=EPSG%3A4326&BBOX=0,90,90,180&token=27e26598e322422db64d9d40e8c9aaa2

**Comment by NidhalSNSdev** [comment]
So, My problem, Why when i introduce  Sector in Layer spécification g3m use other Sector because when i print sector definition i have this message from library:
12-11 17:14:33.316: I/System.out(2929): &WIDTH=256&HEIGHT=256&BBOX=-90.0,-180.0,0.0,-90.0
12-11 17:14:33.336: I/System.out(2929): &WIDTH=256&HEIGHT=256&BBOX=-90.0,-90.0,0.0,0.0
12-11 17:14:33.376: I/System.out(2929): &WIDTH=256&HEIGHT=256&BBOX=-90.0,0.0,0.0,90.0
12-11 17:14:33.406: I/System.out(2929): &WIDTH=256&HEIGHT=256&BBOX=-90.0,90.0,0.0,180.0
12-11 17:14:33.426: I/System.out(2929): &WIDTH=256&HEIGHT=256&BBOX=0.0,-180.0,90.0,-90.0
12-11 17:14:33.466: I/System.out(2929): &WIDTH=256&HEIGHT=256&BBOX=0.0,-90.0,90.0,0.0
12-11 17:14:33.486: I/System.out(2929): &WIDTH=256&HEIGHT=256&BBOX=0.0,0.0,90.0,90.0
12-11 17:14:33.546: I/System.out(2929): &WIDTH=256&HEIGHT=256&BBOX=0.0,90.0,90.0,180.0

**Comment by mdelacalle** [comment]
I don’t know if I understanding, G3M never use one petition, we make several petitions depending where your camera are. Finally the complete map is composed with the tiles downloaded in different requests.

If you want to know how g3m works here we have a paper where is explained:
http://www.glob3mobile.com/wp-content/uploads/2012/07/glob3_mobile_COMGEO2012.pdf

Thank you

**Comment by NidhalSNSdev** [comment]
So problem is: When status tiles Download is 404 screen is blocked and layer is not charged

**Comment by mdelacalle** [comment]
If you have nothing to show the globe is not ready and never starts.
Exactly what are you trying to do?
You can control when start your application using InitializationTasks.
Please read that thread to know how:

https://github.com/glob3mobile/g3m/issues/13

Thank you
