### ISSUE TITLE
Camera.setGeodeticPosition() 'look-down issue'

### ISSUE THREAD

**Issue by akosmaroy** [glob3mobile/g3m#17]
I've encountered a strange issue: when setting the camera position & angle & pitch frequently, the camera view starts to 'flicker'. after investigating the issue, my conclusion is that this is caused by Camera.setGeodeticPosition() setting a setPitch(Angle.zero()); and the re-setting both heading & pitch to the 'old value'

the easiest way to reproduce this is to call setGeodeticPosition() paralelly in an asnyc manner

but even when this is called sequentially (say via a synchronized function only), it will still display this effect, if these setters are called frequently enough.

can provide source code if needed for verification

**Comment by DiegoGomezDeck** [comment]
Hello Akos,

The problem you describe "smells" like a multithreading problem.  Let me state the multithreading politics in g3m.
- All the calls to g3m api must be done in the opengl thread.
- Being a multiplatform framework, this is "tricky" as iOS uses the main-thread for opengl, Android uses a exclusive thread for OpenGL (it's not the UI thread), and HTML5 version use just one thread for everything (you know, there are not threads in javascript).
- There are a set of options for executing your code into the renderer (opengl) thread.
  - IThreadUtils::invokeInRendererThread(GTask\* task, bool autoDelete).  This method enqueue the execution of the given GTask into the renderer thread.   It's the basic method, but usually it's too low level for common cases.
  - Call-backs from the downloader.   The downloader is a key component of the framework.   It handles downloading of bitmaps and buffers asynchronously.  The both listeners (IBufferDownloadListener and IImageDownloadListener) are invoked in the renderer thread.   So in case you need to change something in the g3m based on the result of a download, this is the recommended method. 
  - GInitialiazationTask:  Initialization tasks are meant to serve for custom-initialization tasks programmed by the user of the framework.   It provides a safe-point for doing such initialization.  By "safe" I mean:  The g3m is full initialized AND the initialization task will be executed in the renderer thread.
  - Periodical Tasks:  G3M provides a mechanism for execution of tasks periodically.   PeriodicalTask is just a pair of a GTask and in interval.   If you need to update the g3m, for instance, N times per minute... this is your option.  Again, the GTask is invoked in the renderer thread.

Long history short:  All the callbacks/listener mechanism that G3M provides provide you a safe way to execute your code in the correct thread.  Based on your needs you can use InitializationTask, PeriodicalTask, Downloader-listeners or the more low-level IThreadUtils::invokeInRendererThread().

**Comment by akosmaroy** [comment]
thanks for the info.

no it seems that I need to use ThreadUtils_Android.invokeInRendererThread() - where the constructor for ThreadUtils_Android is package visible only, and the G3MBuilder_Android.createDefaultThreadUtils() is also package visible only. thus I don't have access to this.

moreover, it would be nice to have a clarification on _what_ function calls need to be invoked this way. I see now that setting camera views are such calls though :)

**Comment by DiegoGomezDeck** [comment]
Hello Akos,

All the classes named XXX_Platform (where platform, for today, are _iOS _Android and _WebGL) are not intended to be instanced by nobody but the core.   To get an instance of those classes, you have to use G3MContext.  G3MContext are always a parameter for callback-listeners, tasks, etc.

And for your case, you can ask the widget for the context.

G3MWidget::getG3MContext()

And from there:  context->getThreadUtils()

**Comment by akosmaroy** [comment]
thanks, with the above it works fine
