### ISSUE TITLE
ability to change the camera field of view?

### ISSUE THREAD

**Issue by akosmaroy** [glob3mobile/g3m#19]
I wonder how would one change the camera field of view, so that a wider angle camera view is made possible?

I'm looking at Camera::calculateFrustumData(), and it seems the _tanHalfFieldOfView value would specify this angle, which is a burned-in constant. if I change this I seem to get expected results.

can you please confirm that indeed this is the way of changing the field of view

would you be open to change the API so that this value can be changed from outside of the library, through a public method?

**Comment by DiegoGomezDeck** [comment]
In the current implementation, the FOV is hardcoded to something like 42 degrees and it's not posible to change it.

**Comment by akosmaroy** [comment]
since then, a function has been added to allow setting FOV
