### ISSUE TITLE
please add renderTileMeshes option to PlanetRenderer

### ISSUE THREAD

**Issue by akosmaroy** [glob3mobile/g3m#20]
so that one can enable / disable mesh rendering not just when building the planet renderer, but after it has been built as well

thank you

(sorry for not sending a patch - I haven't set up C++ -> Java translation yet)

**Comment by DiegoGomezDeck** [comment]
Done! (in purgatory).   Please give it a try, I didn't test it for myself.

**Comment by akosmaroy** [comment]
works, thank you!
