### ISSUE TITLE
Show balloon after touch mark(Android)

### ISSUE THREAD

**Issue by dambroz** [glob3mobile/g3m#201]
Hello. I want show balloon with text after touch on mark.
for example:
![google-map-balloon](https://cloud.githubusercontent.com/assets/6553083/19078445/d0624f58-8a58-11e6-9216-734ac261a8ef.jpg)
I find TextCanvasElement.class and BalloonCanvasElement.class, but i don't understand how i can use it.
How I can show balloon with description after touch?

**Comment by mdelacalle** [comment]
Hi dambroz.

You have to create the UI using regular Android classes.
Check the example on the demo -->  https://github.com/glob3mobile/g3m/blob/purgatory/Android/G3MAndroidDemo/src/org/glob3/mobile/demo/SymbologyActivity.java

Thanks for using Glob3 Mobile. If you need further assistance don't hesitate to contact with us

**Comment by dambroz** [comment]
mdelacalle, thanks for the answer.
