### ISSUE TITLE
Add and remove marks

### ISSUE THREAD

**Issue by octavianiLocator** [glob3mobile/g3m#206]
Hi guys,

Which is the recommended method to add and remove marks on the fly? 
- how to add a mark
- how to remove one mark
- how to remove all marks
- on which thread should each be called?

I am using the following :

**Add mark:** 

```
// runs on UI thread
    mark = new Mark(....);
    _marksRenderer.addMark(mark);
```

**Remove Mark:**

```
// runs on UI thread
    _marksRenderer.removeMark(mark);
```

**Clear globe of all marks:** 

```
// runs on RendererThread
    _marksRenderer.removeAllMarks();
```

**Comment by DiegoGomezDeck** [comment]
Please see issue #17

Basically, every call to every method for every classes of g3m must be done form the OpenGL thread.  G3M provides an utility method for this:  IThreadUtils::invokeInRendererThread().

**Comment by octavianiLocator** [comment]
Awesome. Made all the g3m-method calls to run on OpenGL thread and everything is nice and smooth.
Thanks a ton, @DiegoGomezDeck
