### ISSUE TITLE
Download Layer in Android Application

### ISSUE THREAD

**Issue by NidhalSNSdev** [glob3mobile/g3m#21]
Hi,

In my application i have to add many WMSLayer in some time.
For exemple i have OpenStreetMap Layer and i want to add temperature Layer.But, when temperature Layer is not in cash and i have to download it. and  when downloading I want to save globe and Open Street Map Layer avaliable for user.

So, Downloading  layer in Background (Without black screen for user and save globe state ) and when finish add layer in globe.

Solution to do this?

thanks

**Comment by mdelacalle** [comment]
I need to clarify exactly what you want to do.

Do you want to work with offline layers??, in that case you have to fill the cache and play with enable and disable property,
There are several ways for do that, depending the kind of information.
There isn’t a magical solution, the API gives you all you need depending you have.

Thank you

**Comment by NidhalSNSdev** [comment]
No, it's not offline.

My question is how  can i enable Layer with setEnable(true) without delete map from screen for user.

Now, if i have globe with OSM Layer and when i enable Temperature Layer OSM Layer is not visible for user.

So, download layer in background and enable it without  losing the display of the original map

**Comment by NidhalSNSdev** [comment]
to simplify, how can i download WMSLayer and save it in cache without display it in map ?

**Comment by mdelacalle** [comment]
Yes you can download any layer for be used, actually all the tiles that you are downloading are stored on cache.

In this readme you can see how you can prepare and android app to download the layer you want, this cache could be use wherever lately.:
https://github.com/glob3mobile/g3m/blob/purgatory/tools/precachingReadme.txt

To enable, disable layers you can see how is this management in : 
https://github.com/glob3mobile/g3m/blob/purgatory/Android/G3MAndroidDemo/src/org/glob3/mobile/demo/SimplestRasterActivity.java

Pay attention to the transparency and which is the base layer and things like that.
Thank you
