### ISSUE TITLE
 load online terrain

### ISSUE THREAD

**Issue by venci01** [glob3mobile/g3m#214]
hi,@DiegoGomezDeck 
i am studying glob3mobile,but i don not know how to load online terrain 

http://worldwind26.arc.nasa.gov/wms

<?xml version="1.0" encoding="UTF-8"?>

<ElevationModel version="1" modelType="Compound">
    <ElevationModel version="1">
        <DisplayName>USA 10m, World 30m, Ocean 900m</DisplayName>
        <Service serviceName="OGC:WMS" version="1.3">
            <GetCapabilitiesURL> http://worldwind26.arc.nasa.gov/wms</GetCapabilitiesURL>
            <GetMapURL>http://worldwind26.arc.nasa.gov/wms</GetMapURL>
            <LayerNames>NASA_SRTM30_900m_Tiled,aster_v2,USGS-NED</LayerNames>
        </Service>
        <RetrievePropertiesFromService>true</RetrievePropertiesFromService>
        
        <LastUpdate>16 01 2014 20:00:00 GMT</LastUpdate>
        <DataCacheName>Earth/EarthElevations2</DataCacheName>
        <ImageFormat>application/bil16</ImageFormat>
        <DataType type="Int16" byteOrder="LittleEndian"/>
        <DataDetailHint>0.30</DataDetailHint>
        <FormatSuffix>.bil</FormatSuffix>
        <ExtremeElevations min="-11000" max="8850">
            <FileName>config/SRTM30Plus_ExtremeElevations_5.bil</FileName>
        </ExtremeElevations>
        <NumLevels count="9" numEmpty="0"/>
        <TileOrigin>
            <LatLon units="degrees" latitude="-90" longitude="-180"/>
        </TileOrigin>
        <LevelZeroTileDelta>
            <LatLon units="degrees" latitude="20" longitude="20"/>
        </LevelZeroTileDelta>
        <TileSize>
            <Dimension width="150" height="150"/>
        </TileSize>
        <Sector>
            <SouthWest>
                <LatLon units="degrees" latitude="-90" longitude="-180"/>
            </SouthWest>
            <NorthEast>
                <LatLon units="degrees" latitude="90" longitude="180"/>
            </NorthEast>
        </Sector>
    </ElevationModel>
</ElevationModel>

**Comment by venci01** [comment]
<?xml version="1.0" encoding="UTF-8"?>



<ElevationModel version="1" modelType="Compound">
    <ElevationModel version="1">
        <DisplayName>USA 10m, World 30m, Ocean 900m</DisplayName>
        <Service serviceName="OGC:WMS" version="1.3">
            <GetCapabilitiesURL> http://worldwind26.arc.nasa.gov/wms</GetCapabilitiesURL>
            <GetMapURL>http://worldwind26.arc.nasa.gov/wms</GetMapURL>
            <LayerNames>NASA_SRTM30_900m_Tiled,aster_v2,USGS-NED</LayerNames>
        </Service>
        <RetrievePropertiesFromService>true</RetrievePropertiesFromService>
        
        <LastUpdate>16 01 2014 20:00:00 GMT</LastUpdate>
        <DataCacheName>Earth/EarthElevations2</DataCacheName>
        <ImageFormat>application/bil16</ImageFormat>
        <DataType type="Int16" byteOrder="LittleEndian"/>
        <DataDetailHint>0.30</DataDetailHint>
        <FormatSuffix>.bil</FormatSuffix>
        <ExtremeElevations min="-11000" max="8850">
            <FileName>config/SRTM30Plus_ExtremeElevations_5.bil</FileName>
        </ExtremeElevations>
        <NumLevels count="9" numEmpty="0"/>
        <TileOrigin>
            <LatLon units="degrees" latitude="-90" longitude="-180"/>
        </TileOrigin>
        <LevelZeroTileDelta>
            <LatLon units="degrees" latitude="20" longitude="20"/>
        </LevelZeroTileDelta>
        <TileSize>
            <Dimension width="150" height="150"/>
        </TileSize>
        <Sector>
            <SouthWest>
                <LatLon units="degrees" latitude="-90" longitude="-180"/>
            </SouthWest>
            <NorthEast>
                <LatLon units="degrees" latitude="90" longitude="180"/>
            </NorthEast>
        </Sector>
    </ElevationModel>
</ElevationModel>

**Comment by mdelacalle** [comment]
The terrain feature is under severe refactoring those days, but you can use easily the class ElevationDataProvider.
You have an Android example here (on the iOS demo you'll have the same example): 
https://github.com/glob3mobile/g3m/blob/purgatory/Android/G3MAndroidDemo/src/org/glob3/mobile/demo/ScenarioTerrainActivity.java

You only have to:

       final float verticalExaggeration = 2f;
      final double deltaHeight = -700.905;   // this delta is used for the camera, if your terrain is close to the sea or is the whole world 0 is a good number.


// This is the sector where you have terrain
      final Geodetic2D lower = new Geodetic2D( //
               Angle.fromDegrees(40.1665739916489), //
               Angle.fromDegrees(-5.85449532145337));
      final Geodetic2D upper = new Geodetic2D( //
               Angle.fromDegrees(40.3320215899527), //
               Angle.fromDegrees(-5.5116079822178570));

      final Sector demSector = new Sector(lower, upper);

      // NROWS          1335
      // NCOLS          2516
      // You have to put the bil file under assets folder and you have to put the number of rows and      //columns  for your dataset
      final ElevationDataProvider elevationDataProvider = new SingleBilElevationDataProvider(new URL("file:///0576.bil", false),
               demSector, new Vector2I(2516, 1335), deltaHeight);

      builder.getPlanetRendererBuilder().setElevationDataProvider(elevationDataProvider);
      builder.getPlanetRendererBuilder().setVerticalExaggeration(verticalExaggeration);


Thanks for using it.

Best regards
