### ISSUE TITLE
Pinch to zoom Listner and save globe orientation

### ISSUE THREAD

**Issue by NidhalSNSdev** [glob3mobile/g3m#22]
Hi,

I have 2 question:

   1: How can i add zoom  listner ( or camera distance listner)  for globe on pich zoom.

   2: How can i disable map rotation relative his  center (  I want this: scroll/drag N / S or W / E but the card must remain oriented N / S (no rotation))

Thanks

**Comment by DiegoGomezDeck** [comment]
Hello,

About the point 1, please take a look to those methods in PlanetRenderer:

  /**
   Add a listener for notification of visible-sector changes.

   @param stabilizationInterval How many time the visible-sector has to be settled (without changes) before triggering the event.  Useful for avoid process while the camera is being moved (as in animations).  If stabilizationInterval is zero, the event is triggered immediately.
   _/
  void addVisibleSectorListener(VisibleSectorListener_ listener,
                                const TimeInterval& stabilizationInterval);

  /**
   Add a listener for notification of visible-sector changes.

   The event is triggered immediately without waiting for the visible-sector get settled.
   _/
  void addVisibleSectorListener(VisibleSectorListener_ listener);

**Comment by DiegoGomezDeck** [comment]
Related to the point 2, take a look to class ICameraConstrainer and subclasses.   Basically you can add a camera-constrainer using the builder's method addCameraConstrainer().

**Comment by NidhalSNSdev** [comment]
Thanks very much, I resolve my problem after your response.

**Comment by DiegoGomezDeck** [comment]
See issue #41 for a more detailed explanation about ICameraConstrainer

**Comment by break2k** [comment]
Hey NidhalSNSdev,
would you like to tell me how you resolved your problem leaving north and south untouched.

**Comment by NidhalSNSdev** [comment]
Hey break2k,

To resolve this Problem you can add  addCameraConstraint to builder and control nextCamera

```
builder.addCameraConstraint(new ICameraConstrainer() {

                @Override
                public boolean onCameraChange(Planet planet,
                        Camera previousCamera, Camera nextCamera) {
                    // TODO Auto-generated method stub

                    nextCamera.setHeading(Angle.zero());


                    if (nextCamera.getGeodeticPosition()._height > maxZoomIn2D) {
                        nextCamera.setGeodeticPosition(
                                new Geodetic2D(Angle.zero(), Angle.zero()),
                                maxZoomIn2D);
                    }



                    return false;
                }


                @Override
                public void dispose() {
                    // TODO Auto-generated method stub

                }
            })
```

**Comment by break2k** [comment]
Thanks Dude :) :+1: 

You earned this:
![thanks_0116](https://f.cloud.github.com/assets/506722/2039367/cbab41de-899f-11e3-8798-4384596acd34.gif)
