### ISSUE TITLE
setCameraPosition() doesn't work with elevation set to 0

### ISSUE THREAD

**Issue by akosmaroy** [glob3mobile/g3m#23]
when calling G3MWidget_Android.setCameraPosition() with an elevation of value 0, the camera setting does not have any effect.

when calling with a non-zero (positive) value, it seems to work fine

**Comment by akosmaroy** [comment]
and it doesn't seem to work when set to a negative number either. these elevation readings come from a live GPS

**Comment by DiegoGomezDeck** [comment]
You can code a "Null" CameraConstrainer that simply does nothing.  But take in mind the camera can pass through the terrain.
