### ISSUE TITLE
Memory leak found

### ISSUE THREAD

**Issue by DiegoGomezDeck** [glob3mobile/g3m#24]
It happens with the iPad is rotated.

![screen shot 2013-12-17 at 2 10 38 pm](https://f.cloud.github.com/assets/1429156/1767088/fdbf4ff8-674e-11e3-8605-1eb70d01ebe9.png)

![screen shot 2013-12-17 at 2 11 59 pm](https://f.cloud.github.com/assets/1429156/1767096/24b81b62-674f-11e3-967d-a42390dd4799.png)

![screen shot 2013-12-17 at 2 13 45 pm](https://f.cloud.github.com/assets/1429156/1767109/67d4d5b6-674f-11e3-8e74-d90849b6fbf1.png)

**Comment by amazingsmash** [comment]
Leak fixed.
