### ISSUE TITLE
WMS Layer add in globe3D ?

### ISSUE THREAD

**Issue by NidhalSNSdev** [glob3mobile/g3m#3]
How i can add WMS Layer in 3D glob?

**Comment by NidhalSNSdev** [comment]
I use G3m for android application.Thanks

**Comment by mdelacalle** [comment]
Hello, Thank you for using G3M framework
You can find an example in the next class:

https://github.com/glob3mobile/g3m/blob/purgatory/Android/G3MAndroidDemo/src/org/glob3/mobile/demo/SimpleRasterLayerBuilder.java

where:

```
 final WMSLayer blueMarble = new WMSLayer("bmng200405", new URL("http://www.nasa.network.com/wms?", false),
           WMSServerVersion.WMS_1_1_0, Sector.fullSphere(), "image/jpeg", "EPSG:4326", "", false, new LevelTileCondition(0,
                    18), TimeInterval.fromDays(30), true);
```

You can define the layer  with the following params:
- name of layer
- Server URL
- WMS version
- Sector (Bounding Box) where the layer is defined
- format -> if you no need transparency is better jpeg
- SRS -> EPSG:4326 or EPSG:900913
- isTransparent (boolean)
- LevelTileCondition --> (the levels where the layer is visible
- Time in cache (you can define if the layer have to be updated or if is cached)
- readExpired (true almost always)

you have to define the layer, add to layerset, and create the widget

In this class you can see how to

https://github.com/glob3mobile/g3m/blob/purgatory/Android/G3MAndroidDemo/src/org/glob3/mobile/demo/SimplestRasterActivity.java

Thanks

**Comment by NidhalSNSdev** [comment]
Thanks for your Response,

Yes i used your example but the layer is not showing.
So i can't integrate this example https://www.mapbox.com/mapbox.js/example/v1.0.0/wms/ with G3m with params:
 BBOX=15028131.257091932,-5009377.085697311,20037508.342789244,-7.081154551613622e-10
           FORMAT=image/png
           HEIGHT=256
           LAYERS=RAS_RIDGE_NEXRAD
           REQUEST=GetMap
           SERVICE=WMS
           SRS=EPSG:3857
           STYLES=
           TRANSPARENT=true
           VERSION=1.1.1
           WIDTH=256

**Comment by mdelacalle** [comment]
You are not calling to a WMS server. Please review your layer configuration. This is not a g3m issue.
In that example if you read the mapbox code you can see:
http://gis.srh.noaa.gov/arcgis/services/NDFDTemps/MapServer/WMSServer 

as wms server, you have to define your wms layer with that parameters, mapbox is not a wms service.
If you have a mapbox account try the mapbox layer also included in the code of the example.

best
