### ISSUE TITLE
Problem with MarksRenderer

### ISSUE THREAD

**Issue by NidhalSNSdev** [glob3mobile/g3m#31]
Hi,

I add MarksRendrer in builder for user position.But when i rebuild globe and change from Spherical to FLAT MarksRenderer make error:

For first enabling to marker rendreder it's ok (picture 1) but when i rebuild globe with new builder i have to problem:
                1: In Flat i have a problem in displaying the marker ( picture 2)
                2: In Spheerical planet it's impossible to view the marker 

![device-2013-12-20-100948](https://f.cloud.github.com/assets/2900451/1789387/064ec8e2-6957-11e3-9786-54f62e6bd049.png)
![device-2013-12-20-100612](https://f.cloud.github.com/assets/2900451/1789390/125ef242-6957-11e3-8526-957b09369138.png)

**Comment by NidhalSNSdev** [comment]
I have this in my logcat when iw ant to display marker and never show in globe: <gl_draw_error_checks:575>: GL_INVALID_OPERATION

**Comment by mdelacalle** [comment]
Work in progress... Thanks!

**Comment by DiegoGomezDeck** [comment]
NidhalSNSdev :  Did you make the changes from the Renderer's thread?

**Comment by NidhalSNSdev** [comment]
Yes i use the standard MarksRenderer when i rebuild Map. you can find more details here:
https://github.com/makinacorpus/Meteo-France-Android/blob/master/src/com/makinacorpus/meteofrance/MainActivity.java

**Comment by DiegoGomezDeck** [comment]
From a quick bird-view of your code, I found that you're calling g3m core-methods from android UI thread.

For instance, line 224:
                                                        layerToAdd.setEnable(true);

This is being called from the Android UI.

Please take a look to issue #17

**Comment by NidhalSNSdev** [comment]
Thank you for your reply but I do not understand your comment.
   layerToAdd.setEnable (true) is used to enable the layers defined here

https://github.com/makinacorpus/Meteo-France-Android/blob/master/src/com/makinacorpus/meteofrance/SimpleRasterLayerBuilder.java

and I am based on your demo application for the establishment of system activation and deactivation of layers
https://github.com/glob3mobile/g3m/blob/purgatory/Android/G3MAndroidDemo/src/org/glob3/mobile/demo/SimplestRasterActivity.java

But this problem only appears when I rebuild the globe to render Markers and if this is a problem thread I think it will be the case for all layers not only for markers.

```
    private void addMarkerPosition() {
            userMarkers= new MarksRenderer(false);
            Geodetic2D position = null;
            if (userLocation != null) {

                    position = new Geodetic2D(Angle.fromDegrees(userLocation
                                    .getLatitude()), Angle.fromDegrees(userLocation
                                    .getLongitude()));

            } else {
                    position = new Geodetic2D(Angle.fromDegrees(latitudeToulouse),
                                    Angle.fromDegrees(longitudeToulouse));
                    Toast.makeText(activityContext, geolocationError, Toast.LENGTH_LONG)
                                    .show();

            }
            userMarkers.addMark(new Mark(yourPoisiton, //
                            new URL(markerUrl, false), //
                            new Geodetic3D(position, 0), //
                            AltitudeMode.RELATIVE_TO_GROUND, 0, //
                            true, //
                            14));
            builder.addRenderer(userMarkers);
            userMarkers.setEnable(false);

    }
```

**Comment by DiegoGomezDeck** [comment]
> But this problem only appears when I rebuild the globe to render Markers and if this is a problem thread I think it will be the case for all layers not only for markers.

Not really... As layers change is a very frequent operation, the core in itself protects you from the multithreading stuff.  But it's the exception, not the rule.  The rule is "every change to the core has to be invoked from the renderer thread".
