### ISSUE TITLE
Use offline map or custom texture for globe

### ISSUE THREAD

**Issue by antercepter** [glob3mobile/g3m#35]
Hello!

Does it exist way to use globe without internet connection and without precaching? I have custom map, can I set it to the globe?

**Comment by mdelacalle** [comment]
I need more information, but there are some ways to do that:

 1: Publish your data  in a local server and cache the data, after that you can use the data base g3m.cache in anywhere.
 2: Make a cache pyramid with your file and use the class -> URLTemplateLayer  

We have a tool to convert tiffs in cache , anyway is different depending the platform, etc….

Thanks

**Comment by antercepter** [comment]
But I want to use map from assets or resources in Android. Is it possible to do without database use? I searched in library but didn't find a method which would solve this issue.

**Comment by mdelacalle** [comment]
I understand you want to have a texture file ( a map , I suppose) and you want to read from assets.
There isn’t the method to load the file as a map.
G3M work with tiles, you must to divide images (tiling) when you are changing the camera (zoom in-out)

If you want know more about how g3m works you can read:
http://www.glob3mobile.com/wp-content/uploads/2012/07/glob3_mobile_COMGEO2012.pdf
http://dl.acm.org/citation.cfm?id=2345342#!

Anyway the process to have the image in data base is not so hard.

Thanks

**Comment by antercepter** [comment]
So, must I divide my map to tiles and put them in database, after I will can use database to show tiles on the globe? Where I must store this db in my project? I think in assets, so I need to implement reading db from assets. Did I understand right?

**Comment by mdelacalle** [comment]
Not exactly.

Every tile you download is stored in the database (g3m.cache) on android the path of this database depends of device and version, on the external storage: 
http://developer.android.com/guide/topics/data/data-storage.html#filesExternal  . This process is automatic, you cannot do anything to use that, anyway if you fill the g3m.cache, the app uses that cache before download textures. (The cache first check if you have the texture stored on the local database, if you  have not the texture, the dowloader goes to the path where you have put the texture  —> (Internet,  Assets (file:///…..))

You can save your texture on assets, and the downloader goes to this path (you no need connection).

thanks
