### ISSUE TITLE
How to manipulate globe programatically? 

### ISSUE THREAD

**Issue by antercepter** [glob3mobile/g3m#36]
How to zoom in/out the globe programatically? I need to show globe first that will be zoomed yet. Also I want to rotate globe. I tried to do that using setAnimatedCameraPosition(),  but don't understand how it works.

Thanks.

**Comment by mdelacalle** [comment]
Several examples on demo app:

https://github.com/glob3mobile/g3m/blob/purgatory/Android/G3MAndroidDemo/src/org/glob3/mobile/demo/ShapeSymbolizerActivity.java

```
  _g3mWidget.setAnimatedCameraPosition(Geodetic3D.fromDegrees(39.12787093899339d, -77.59965772558118d, 500000),
           TimeInterval.fromSeconds(8));
```

For example, with this sentence the camera goes to that position in 8 seconds.
Anyway the globe does not rotate, it’s the camera.

Thanks

**Comment by antercepter** [comment]
I tried to move camera, for example, from 1, 1 degrees to 1,90 degrees, height is the same. Camera flies around globe, but distance to globe varies from begin to end. How to set permanent distance to globe? My code:

g3mWidget.setAnimatedCameraPosition(Geodetic3D.fromDegrees(1d, 1d, 10000000),
                   TimeInterval.fromMilliseconds(1));

```
     new Handler().postDelayed(new Runnable() {
            @Override
            public void run() {
                g3mWidget.setAnimatedCameraPosition(Geodetic3D.fromDegrees(1d, 90d, 10000000),
                    TimeInterval.fromSeconds(5));
            }
        }, 1000);
```

Thanks

**Comment by mdelacalle** [comment]
I suggest use tasks for do this, you set the globe at the beginning wherever and use tasks to move it.

https://github.com/glob3mobile/g3m/issues/13

thanks

**Comment by antercepter** [comment]
I set GInitializationTask in builder and called in it 
builder.getPlanetRendererBuilder().setVerticalExaggeration(2f);
but it didn't has effect. What I do wrong?

**Comment by DiegoGomezDeck** [comment]
I guess there two possibilities:

1) You change vertical-exaggeration but you didn't put a terrain-elevation-data provider.

2) You changed the vertical-exaggeration AFTER the builder created the widget.  The builder don't change anything on the widget after the creation step.  If this is the case, you have 2 options:
2.a) call the builder method before the widget creation
2.b) change the VerticalExaggeration with something like:  widget->getPlanetRenderer()-> setVerticalExaggeration()

**Comment by DiegoGomezDeck** [comment]
Did the answers resolve your problem? If yes, can you close the issue?
