### ISSUE TITLE
request: add removeShape() call to Shapes ShapesRenderer

### ISSUE THREAD

**Issue by akosmaroy** [glob3mobile/g3m#37]
MarksRenderer has a removeMark() function, and I wonder if it was possible to add a similar call to ShapesRenderer, that would remove a single shape from the renderer. it would be greatly helpful.

**Comment by DiegoGomezDeck** [comment]
Already done in branch "hud-renderer", it'll merged into "purgatory" soon.

**Comment by akosmaroy** [comment]
great!

**Comment by DiegoGomezDeck** [comment]
Already merged into purgatory branch
