### ISSUE TITLE
Strange "saw" effect in terrain

### ISSUE THREAD

**Issue by DiegoGomezDeck** [glob3mobile/g3m#38]
Check this strange "saw" effect at terrain tessellation

![screen shot 2013-12-30 at 12 02 53 pm](https://f.cloud.github.com/assets/1429156/1823537/830dfd8c-717f-11e3-8471-cf2811f0d1c6.png)

![screen shot 2013-12-30 at 12 02 06 pm](https://f.cloud.github.com/assets/1429156/1823538/96b1a532-717f-11e3-85f0-fcbfb6e6c5e3.png)

**Comment by amazingsmash** [comment]
The effect shown above is more obvious as the tile mesh becomes rawer and verticalExaggeration higher.
![screenshot 2014 02 20 11 58 37](https://f.cloud.github.com/assets/1220012/2420835/b74b989c-ab78-11e3-95b6-d78c3fc8caef.png)

After some experiments, I solved this changing line 219 of ElevationData.cpp to:

result = IMathUtils::instance()->linearInterpolation(heightY, heightNextY, alphaY);

It seemed the values heightY, heightNextY were flipped.
