### ISSUE TITLE
set transparent background

### ISSUE THREAD

**Issue by antercepter** [glob3mobile/g3m#39]
Hello!

I want to set background a repeating video, using VideView. But when I set on builder background transparent color, it doesn't works and background is black.

**Comment by DiegoGomezDeck** [comment]
Hello,

Please to meet you.

We don't support transparent background yet... It's planned to be implemented soon.  (soon = some weeks).

**Comment by vipinkesari** [comment]
hello,

We can set the background transparent of the using only single line code...

mGlSurface.setZOrderOnTop(true);

which is default property of the openGl.
