### ISSUE TITLE
WMS Layer add in globe3D  in Android Application?

### ISSUE THREAD

**Issue by NidhalSNSdev** [glob3mobile/g3m#4]
Hi,

I want to integrrate WMS Layer with g3m and i use:

final WMSLayer blueMarble = new WMSLayer("RAS_RIDGE_NEXRAD", new URL(
                "http://nowcoast.noaa.gov/wms/com.esri.wms.Esrimap/obs?", false),
                WMSServerVersion.WMS_1_1_0, Sector.fullSphere(), "image/png",
                "EPSG:900913", "", false, new LevelTileCondition(0, 18),
                TimeInterval.fromDays(30), true);

full exxample to get from server is :  http://nowcoast.noaa.gov/wms/com.esri.wms.Esrimap/obs?SERVICE=WMS&REQUEST=GetMap&VERSION=1.1.1&LAYERS=RAS_RIDGE_NEXRAD&STYLES=&FORMAT=image%2Fpng&TRANSPARENT=true&HEIGHT=256&WIDTH=256&SRS=EPSG%3A900913&BBOX=-12523442.714243276,5009377.085697313,-11897270.578531113,5635549.221409475

When i show result in my application i have White Globe if isTransparent= false  and  black globe when isTransparent = true.

And when i integrate other layer to suporpose my layer i have a message: "Inconsistency in Layer's Prametres: MErcator "

Thanks for help

**Comment by mdelacalle** [comment]
"Inconsistency in Layer's Prametres: MErcator " means that you are trying to add two layers with different projection.
If you use mercator all layers must be mercator

**Comment by NidhalSNSdev** [comment]
Thanks. But why i have White globe (isTransaprent = false) and Black globe (isTransparent = true ) and not correct layer but whel i check image from server in browser i havae the correct image 
http://nowcoast.noaa.gov/wms/com.esri.wms.Esrimap/obs?SERVICE=WMS&REQUEST=GetMap&VERSION=1.1.1&LAYERS=RAS_RIDGE_NEXRAD&STYLES=&FORMAT=image%2Fpng&TRANSPARENT=true&HEIGHT=256&WIDTH=256&SRS=EPSG%3A900913&BBOX=-12523442.714243276,5009377.085697313,-11897270.578531113,5635549.221409475

**Comment by mdelacalle** [comment]
I don't know it that layer have a global data, and of course you need to put a base layer if you want to see something different than white or the black globe

If you have local data you can use this method to define a scenario:
   builder.setShownSector(YOUR_SECTOR);

**Comment by NidhalSNSdev** [comment]
Thanks for your response.
