### ISSUE TITLE
release Android resources

### ISSUE THREAD

**Issue by antercepter** [glob3mobile/g3m#40]
Hi.

I realized a mechanism for downloading textures from assets. I use globe in a fragment, which I set visible/invisible, and destroy when go to other fragment. I noticed that my heap grows after recreating globe fragment. I think it's copies of textures, that recreates after new fragment creating. How can I release it when calls onDestroy() in fragment? I set there g3mWidget.getG3MWidget().dispose();
builder.dispose();
but it has no effect. Where did textures store and how to clear them?

**Comment by mdelacalle** [comment]
Hello.
We know this problem, in the demo project you have a solution for that, we simply kill the globe when destroy (Android does not release the textures until you kill completely the activity). 
First of all we are sure that the globe is in its own process, you can do this adding:

 android:process=":your_proccess_name"  to the manifest file.

Later you have to kill the activity in onDestroy(), in our case was on BackPressed()

  @Override
   public void onBackPressed() {
      System.exit(0);
   }

You can see that on any activity of the demo project ( https://github.com/glob3mobile/g3m/tree/purgatory/Android/G3MAndroidDemo ) , you can test that the memory is released.

Thanks!
