### ISSUE TITLE
set zoom constraint

### ISSUE THREAD

**Issue by antercepter** [glob3mobile/g3m#41]
Hello!

Thank you very much for you framework and for helping me. Now I have one more question. Is it possible to set zoom range or constraint for max/min zooming? If it's impossible at the moment, can you tell me where I can find code that makes touch/zoom works?

**Comment by DiegoGomezDeck** [comment]
The code that make this works are distributed over the class hierarchy from CameraEventHandler.

BTW, if you want to constraint the camera movement the core provides you a way to do that:  See ICameraConstrainer and subclasses.

To put your own ICameraConstrainer, you can use the setCameraConstrainsts() method in IG3MBuilder class.  In SimpleCameraConstrainer you can see a simple example that constraint the camera to a range of altitudes.  Basically the idea is that you receive a potential invalid camera, in case the camera position is not the one you want just change it into your desired range.
