### ISSUE TITLE
Block drag when Geodectic Position isNaN in Flat Planet

### ISSUE THREAD

**Issue by NidhalSNSdev** [glob3mobile/g3m#42]
Hi,

How can i block drag in gloge when Geodectic position in ICameraConstrainer become isNaN.

I use  ICameraConstrainer Interface an di found the solution when getGeodeticCenterOfView().isNaN() but not when getGeodeticPosition become NaN
So user never show background of globe.

Thanks

**Comment by DiegoGomezDeck** [comment]
Hello Nidhal,

Can you post some example code to debug this case?

TIA.

**Comment by NidhalSNSdev** [comment]
Hello,

To resolve this problem i had neeed to add  function in ICameraConstrainer to builder:

```
                    if (nextCamera.getGeodeticPosition()._height > maxZoomIn2D) {
                        nextCamera.setGeodeticPosition(
                                new Geodetic2D(Angle.zero(), Angle.zero()),
                                maxZoomIn2D);
                    }
```

and update function getViewDirection in org.glob3.mobile.generated.Camera
