### ISSUE TITLE
Get Limits Bounds of Flat Globe?

### ISSUE THREAD

**Issue by NidhalSNSdev** [glob3mobile/g3m#43]
Hi,

How can i get limit on globe in FLAT mode?
Thanks

**Comment by mdelacalle** [comment]
Hello!
You have to define a Sector

```
  final Geodetic2D lower = new Geodetic2D( //
           Angle.fromDegrees(38.1569225644), //
           Angle.fromDegrees(-9.5500388913));
  final Geodetic2D upper = new Geodetic2D( //
           Angle.fromDegrees(38.9859010475), //
           Angle.fromDegrees(-8.5790345107));

  final Sector demSector = new Sector(lower, upper);
```

and after that pass it to the builder.

builder.setShownSector(demSector.shrinkedByPercent(0.1f));

if you are using a terrain model is better show a sector smaller than terrain area --> shrinkedByPercent in other case simply 

builder.setShownSector(demSector);

Thank you

**Comment by NidhalSNSdev** [comment]
Thanks.

This solution resolve 50% of my problem.The second part is how can i limit FLAT Glob Display to screen height/width and not to the middle of screen. ScreenSHot explain the problem.

![device-2014-01-17-113240](https://f.cloud.github.com/assets/2900451/1939459/0d2eab7e-7f63-11e3-8fd4-043de9edc142.png)

**Comment by mdelacalle** [comment]
You can put the camera wherever and play with zoom, position, etc.... with setCameraPosition or setAnimatedCameraPosition.

 _g3mWidget.setAnimatedCameraPosition(Geodetic3D.fromDegrees(39.12787093899339d, -77.59965772558118d, 500000),
               TimeInterval.fromSeconds(8));

**Comment by NidhalSNSdev** [comment]
Yep i can do this but how can I know that the Globe begins to exceed the limit of the screen?

**Comment by mdelacalle** [comment]
Sorry I'm not understanding, the globe is a standard widget in android, the map uses the complete screen, if you are so far you see the background, do you want another behavior?

**Comment by NidhalSNSdev** [comment]
No, for me the problem is why when i drag map  i have a black and drag is stopped when black is cover the middle of screen in height or in widthn.So how i can stop drag  to not see black?

So, user should be never see the black.

**Comment by mdelacalle** [comment]
You can use the CameraConstrains in that case
