### ISSUE TITLE
Custom Texture

### ISSUE THREAD

**Issue by alexrinaldi** [glob3mobile/g3m#44]
Hi I need to load a custom texture for my globe, there is the ability to load textures from PNG files? I read in one of the previous posts that you can go any load texture loading them know a local server, how can this be done?

**Comment by mdelacalle** [comment]
To response properly we need to know exactly what you want to do, some facts:

1) If your png is a georreferenced map, the best way is through a WMS server, you need to server properly the tiles we need to build a multi-resolution globe.
2) if you want to put an single image over the globe, there is currently no way.
3) we have developed some tools to cache and have maps offline, take a look to: 
https://github.com/glob3mobile/g3m/blob/purgatory/tools/precachingReadme.txt

Please tell us more about your need and we will try to help you as better we can.

Thanks and welcome to g3m.
