### ISSUE TITLE
WMS parameters

### ISSUE THREAD

**Issue by DanielLatapie** [glob3mobile/g3m#45]
Hi,

On WMS parameters, we tried to choose a more little BBOX with the command : Sector.fromDegrees(-165.27,-53.15,177.13,78.2) instead of Sector.fullSphere()
It doesn't work and error message show url with bounds set out of our bbox.
Here is the list of bbox in url error messages :

-90.0,0.0,0.0,78.2 
-90.0,0.0,0.0,78.2 
0.0,-53.15,90.0,0.0 
0.0,-53.15,90.0,0.0 
-90.0,-53.15,0.0,0.0 
-90.0,-53.15,0.0,0.0 
0.0,0.0,90.0,78.2 
0.0,0.0,90.0,78.2

On these parameters, we can set SRS but we can't set CRS which has a default value EPSG:4326.
If we want to join a WMS which provide EPSG:2154 for example. It doesn't work.
How could we set CRS value ?

If the base url of WMS already get a parameter (precede by a "?") the method which make the full request put another "?" in the url instead of a "&".
(Example : http://azar.akka.eu/cgi-bin/mapserv?map=maps/azardev.map?REQUEST=GetMap&SERVICE=WMS&VERSION=1.3.0&WIDTH=256&HEIGHT=256&BBOX=0.0,41.122,18.3832,50.6373&CRS=EPSG:4326&LAYERS=ScanMilAIP&FORMAT=image/png&SRS=EPSG:4326&STYLES=&TRANSPARENT=TRUE)

Finally, can we choose the projection of the map returned (to force server send Mercator or not) ? And how ?

Thanks !

**Comment by mdelacalle** [comment]
Hi Daniel.

It seems the bbox is not properly builded:

For example this is a valid sector:

```
  final Geodetic2D lower = new Geodetic2D( //
           Angle.fromDegrees(40.1665739916489), //   --> SOUTH
           Angle.fromDegrees(-5.85449532145337));     --> WEST
  final Geodetic2D upper = new Geodetic2D( //
           Angle.fromDegrees(40.3320215899527), //         -->NORTH
           Angle.fromDegrees(-5.5116079822178570));      --> EAST
   final Sector demSector = new Sector(lower, upper);
```

Set SRS or CRS depends of WMS versión, anyway g3m supports EPSG:4326 or EPSG:900913, you must re-project on server.

The ? , & problem seems a bug, we look the code and we try to fix immediately.

The final map must be web-mercator or wgs84, and the layers can't be mixed in the different projections, we have deployed g3m to use reprojected data (we prefer this work on server, where you have more resources)

**Comment by DanielLatapie** [comment]
Thank you !

We will try to adapt server for stacking all the projections we need.

Nevertheless, we encounter a scaling problem. When we call a WMS from G3M we got the image only with a small scale (with a large scale, no images are displayed).
Whereas when we call the WMS with an other tool (like Quantum GIS) the image is well displayed with a small and with a large scale.
It happens only with this WMS
Do you have an idea of this problem ?

Here is the url : http://azar.akka.eu/cgi-bin/mapserv?map=maps/azar_4326.map&REQUEST=GetMap&SERVICE=WMS&VERSION=1.3.0&WIDTH=256&HEIGHT=256&BBOX=41.1800,-9.6200,51.5400,10.3000&CRS=EPSG:4326&LAYERS=ScanMilAIP&FORMAT=image/png&SRS=EPSG:4326&STYLES=&TRANSPARENT=TRUE

Thanks for your help and your reactivity !
Have a good weekend !

**Comment by mdelacalle** [comment]
Hi Daniel
Definitively this layer is not working properly, when g3m makes petition with more resolution, the server responses a white image and no error, please look your map server conf.

For example:

http://azar.akka.eu/cgi-bin/mapserv?map=maps/azar_4326.map&REQUEST=GetMap&SERVICE=WMS&VERSION=1.3.0&WIDTH=256&HEIGHT=256&BBOX=4.21875%2C45.0%2C5.625%2C46.406250&CRS=EPSG:4326&LAYERS=ScanMilAIP&FORMAT=image/jpeg&SRS=EPSG:4326&STYLES=&TRANSPARENT=FALSE

For this petition , the server responses with no error and no data.

2 things that can help you.
1 -> The '?' problem: 
- Could you paste here how exactly are you creating the layer (The new WMSLayer)
  or
- You can use instead the urlTemplateLayer for that:
  
    final URLTemplateLayer azar4326testlayer = URLTemplateLayer.newWGS84(
             "http://azar.akka.eu/cgi-bin/mapserv?map=maps/azar_4326.map&REQUEST=GetMap&SERVICE=WMS&VERSION=1.3.0&WIDTH=256&HEIGHT=256&BBOX={lowerLongitude}%2C{lowerLatitude}%2C{upperLongitude}%2C{upperLatitude}0&CRS=EPSG:4326&LAYERS=ScanMilAIP&FORMAT=image/jpeg&SRS=EPSG:4326&STYLES=&TRANSPARENT=FALSE",
             Sector.fullSphere(), true, 0, 18, TimeInterval.fromDays(30), true, new LevelTileCondition(0, 18));

2) for this cases we have developed a new method that enable debugging layers

  builder.getPlanetRendererBuilder().setLogTilesPetitions(true);

make pull to g3m and you will have the petition that g3m makes , this can help you to debug.

Thank you!

**Comment by DanielLatapie** [comment]
I create the WMSLayer like this. It was created in a LayerBuilder class like in the G3MAndroidTestingApplication Project.

final Geodetic2D lowerAzar = new Geodetic2D( //
                Angle.fromDegrees(41.122), //   --> SOUTH
                Angle.fromDegrees(-8.28403)); //    --> WEST
        final Geodetic2D upperAzar = new Geodetic2D( //
                Angle.fromDegrees(50.6373), //         -->NORTH
                Angle.fromDegrees(18.3832)); //     --> EAST
        final Sector demSectorAzar = new Sector(lowerAzar, upperAzar);
        final WMSLayer azarLayer = new WMSLayer(
                "ScanMilAIP",
                new URL("http://azar.akka.eu/cgi-bin/mapserv?map=maps/azar_4326.map", false),
                WMSServerVersion.WMS_1_3_0,
                demSectorAzar,
                "image/png",
                "EPSG:4326",
                "",
                true,
                new LevelTileCondition(0, 18),
                TimeInterval.fromDays(30),
                true
        );
        azarLayer.setTitle("Azar France");
        azarLayer.setEnable(false);
        layerSet.addLayer(azarLayer);

I will try other solutions you gave.

**Comment by DanielLatapie** [comment]
I've tried URLTemplateLayer as you defined but I always have a white layer on all the planet.

Despite that, I've found a solution only in setting transparency to false is the code of my precedent message.
In that way, image is displayed in each scale.

**Comment by mdelacalle** [comment]
Great,
I think is a server configuration problem, g3m only make the petitions, the server not responses an error but the image is in white.
If you find any strange behavior in that (the raster layer support) please tell us to fix it.
Thanks!

**Comment by DiegoGomezDeck** [comment]
Hello,

Related to the WMSLayer instantiation, the problem is in the URL.

new URL("http://azar.akka.eu/cgi-bin/mapserv?map=maps/azar_4326.map", false),

Basically your're trying to put an extra-parameter ( map=maps/azar_4326.map ).   To do this, WMSLayer provides an specific method  ( setExtraParameter ).

In this case, you need to instantiate the layer with something like that:

WMSLayer wmsLayer = new WMSLayer( ....,  
     new URL("http://azar.akka.eu/cgi-bin/mapserv"),  // note the URL has not any get parameter
      ...   );
wmsLayer.setExtraParameter("&map=maps/azar_4326.map"); // note the '&' instead of an '?'

**Comment by DanielLatapie** [comment]
Thanks for this clarification.
It works well !
