### ISSUE TITLE
Rounding Issues for Matrix/Viewport

### ISSUE THREAD

**Issue by break2k** [glob3mobile/g3m#46]
Hey guys,

after setting a camera constraint to the zero Vector to block the axis and keep the north/south ratio alive i got an error with the view port/matrix.

The globe moves off the camera screen when i'm trying to rotate a little bit more (especially when i am zoomed out very far).

Any ideas how to fix it? This is an iOS only bug. The same thing works great on Android.

I assume it is a bug with converting the doubles or the values below zero.

best regards
break2k

**Comment by DiegoGomezDeck** [comment]
Hello,

Can you send us some code (or, at least, the problematic camera position) to reproduce it?

Thanks in advance.

**Comment by break2k** [comment]
Hey Diego,

here is the code from my camera constraint

// block axis for pinching and let north / south at their positions
    const Angle zeroAngle = Angle(Angle::zero());
    nextCamera->setHeading(zeroAngle);

i will upload a video in some minutes

**Comment by break2k** [comment]
http://smith.dunkelstern.de/super_awesome.mov <-- an example how the globe is walking off

**Comment by DiegoGomezDeck** [comment]
Hello break2k ;)

What is happening is that the piece of code in charge of processing the SingleFinger-drag (class CameraSingleDragHandler) event is not prepared to handle the situation with a fixed heading.

All the current camera handlers use the invariant that, one time the user put the finger (or fingers) on any lat/lot position.... the lat/lon position under the finger(s) is keep constant don't care where you move the finger(s).  To do that, a lot of "complex" transformations (rotations, translations, etc) are performed to make this invariant fixed.

In this case, "hacking" of heading in the camera-contrains basically breaks this invariant.

To "fix" this issue, we have to create another SingleFinger-drap handler that response to the one-touch-drag-event in a different way.

**Comment by break2k** [comment]
Thanks Diego :) Building an own gestureRecognizer would be a little bit too much work in our time frame. We will think about a reset of the viewport / the globe to a position that will animate it back to the center.
