### ISSUE TITLE
3D Polygon

### ISSUE THREAD

**Issue by DanielLatapie** [glob3mobile/g3m#48]
Hi

Is there a way to draw 3D polygon on a planet ?

I've found BoxShape and QuadShape but it's a 3D square or a flat 2D rectangle.
I would like to draw a 2D Polygon and give him a low height and a high height to make volume.

Thanks !

**Comment by DiegoGomezDeck** [comment]
Hello Daniel,

For rendering 3d objects, there are a couple of options.
- You can render Boxes, Circles, Ellipsoids and Quads in a simple way.
- You can also create a Mesh (see for the subclasses of mesh) and put it into a MeshShape.
- You can render "complex" 3d models using SceneJSShapesParser.  In the directory Blender/io_scene_scenejs/ you will find a blender plugin that convert any blender 3d model into the json-format we're using.

Let me know if any of the options works for you.

**Comment by DanielLatapie** [comment]
Hi Diego,

Thanks for your help.

Boxes and Mesh dont allow us to make complex 3D objects.
Circles, Ellipsoids and Quads are only in 2D.

We are currently trying to use Blender to modelize for exporting 3D objects.
We will keep you informed.

**Comment by DiegoGomezDeck** [comment]
Hi Daniel,

Just to put it a little more clear:

> Circles, Ellipsoids and Quads are only in 2D.
> Circle and Quads are 2D, but full positionable in 3d space..... There are like "planes" living on a 3d world.
> EllipsoidShape is full 3D.

**Comment by DanielLatapie** [comment]
I've tried the SGShape to draw my polygon and it works well ! Thanks !

To configure it, I want to draw solid border in red and draw the rest of the polygon in a translucent red but whatever configuration I set, I always have a full red polygon.

Here is the json for the shape :
{"type":"node","id":"root","nodes":[
  {"type":"material","baseColor":{"r":1,"g":0,"b":0,"a":0.5},"specularColor":{"r":1,"g":0,"b":0},"nodes":[
      {"type":"geometry","primitive":"triangles","id":""
      ,"positions":[-8459,8412,7500,
  -13206,690,7500,
  -2352,-2754,7500,
  10053,-8412,7500,
  13206,-2882,7500,
  -8459,8412,2500,
  -13206,690,2500,
  -2352,-2754,2500,
  10053,-8412,2500,
  13206,-2882,2500
       ]
      ,"indices":[0,1,2,0,2,4,2,3,4,5,6,7,5,7,9,7,8,9,0,5,6,6,1,0,1,2,7,7,6,1,2,3,8,8,7,2,3,4,9,9,8,3,0,4,5,5,9,0]
      }
  ]}
]}

And here is the SGShape creation :
final SGShape sgs = SceneJSShapesParser.parseFromJSON(json,
                "",
                true,
                new Geodetic3D(Geodetic2D.fromDegrees(45.726, 2.278), 5000),
                AltitudeMode.RELATIVE_TO_GROUND
        );

**Comment by DiegoGomezDeck** [comment]
Hello Daniel,

The geometry described in this .json is composed only of triangles.   If you want to draw the edges, you need to create another geometry with "primitive": "lines" (or "line-loop" or "line-strip").
