### ISSUE TITLE
Add Support to token in WMS Layer 

### ISSUE THREAD

**Issue by NidhalSNSdev** [glob3mobile/g3m#5]
Hi,

To get data from server we need sometimes and for reason of security to use a token to identify connection and authentification. In this time probably g3m  not support add token params when i initialized a WMS Layer.

Thanks

**Comment by mdelacalle** [comment]
Try the URLTemplateLayer, you can pass your token into the URL , there is an example in the class SimpleRasterLayerBuilder.java on the Android Demo project.
