### ISSUE TITLE
remove proxy access to map tiles for GWT

### ISSUE THREAD

**Issue by akosmaroy** [glob3mobile/g3m#54]
most of the map tile providers offer Cross-Origin Resource Sharing (aka CORS) headers, thus the proxy-based approach to access these tiles is not needed. please update the GWT code so that for these sources, the proxy is not used. or maybe, one can specify if he wants to use the proxy or nor.

regarding CORS: http://enable-cors.org/

**Comment by DiegoGomezDeck** [comment]
Hello Akos,

The functionality you're asking for is already available in g3m-html5 version.

To avoid using a proxy, do the following in the builder before constructing the widget:

```
  final G3MBuilder_WebGL builder = new G3MBuilder_WebGL();

  final String proxy = null;  // null means no proxy
  builder.setDownloader(
        new Downloader_WebGL(8, // maxConcurrentOperationCount
                                                 10, // delayMillis
                                                 proxy));
```

Hope this helps.

**Comment by akosmaroy** [comment]
indeed, this disables the proxy

the issue with alternate map tiles, for cross origin to work, is hindered by the fact that the URL requests made by the map downloader are HTTP requests with the OPTIONS method - which is typically not allowed. if the same requests would be made using the GET method, things would work fine.

I looked at the Downloader_WebGL_Handler_DefaultImpl class, and didn't find obvious reasons for the OPTIONS method :(

**Comment by akosmaroy** [comment]
to see working pure JavaScript (proxy-less) samples using leaflet.js, see: http://akos.maroy.hu/~akos/leaflet/google.html - for a Google Map version and http://akos.maroy.hu/~akos/leaflet/bing.html for a Bing Map version

**Comment by akosmaroy** [comment]
I did a little bit more of an investigation.

the OPTION method is used by XMLHttpRequest, because an extra header (Cache-Control) is set for it. removing this from the code, Google Map tiles are downloaded fine.

but, Bing won't work, as the metadata request doesn't have CORS headers set. I looked at how this is solved in CesiumJS, and they are using JSONP as a workaround: http://en.wikipedia.org/wiki/JSONP

actually there is JSON support for GWT here: http://www.gwtproject.org/javadoc/latest/com/google/gwt/jsonp/client/JsonpRequestBuilder.html  - so the same approach can be used for G3M as well

**Comment by DiegoGomezDeck** [comment]
Hello Akos,

A couple of questions:
- The changes you made on Downloader_WebGL_Handler_DefaultImpl are in good shape to be published?  Does it need changes in the shared sources?
- About BingMaps:  Not sure how to handle it in a multi-platform way (take in mind that, today, 100% of the layers/layerset code is multiplatform).   This is one of the reasons we considered in time where we choose the option to put a proxy for those cases.

-- Diego

**Comment by akosmaroy** [comment]
regarding bing tiles, I created a new bing tile class, which uses JSONP to get the Bing metadata. it's a replicate of the original BingMapsLayer class, with a change in the initialize function, see here: https://gist.github.com/akosmaroy/9453330

as you see, a minimal amount of magic is needed to get JSONP working - it's mainly related to the fact that the JSON returned by Bing is automatically parsed into objects by the JavaScript engine, and I have to get it back to string form so that G3M's JSON parser can parse it again.

but, with this approach there is an issue. the thing is when this class is used, the G3M code assumes that it is ready right after a call to initialize() - which in this case is not true. even though there are provisions so that the class signals a busy state, this is not handled correctly. in PlanetRenderer, we have:

```
      _layerTilesRenderParameters = _layerSet.createLayerTilesRenderParameters(_errors);
      if (_layerTilesRenderParameters == null)
      {
        ILogger.instance().logError("LayerSet returned a NULL for LayerTilesRenderParameters, can't render planet");
      }
```

with LayerSet returning null if things are not ready:

```
    if (layerSetNotReadyFlag)
    {
      return null;
    }
```

I wonder if this is in fact an error in the PlanetRenderer, and if it should wait until layers are ready
