### ISSUE TITLE
How can I render antialiasing line?

### ISSUE THREAD

**Issue by hanchao** [glob3mobile/g3m#55]
My code like this:

```
  Mesh* result = new IndexedMesh(GLPrimitive::lineLoop(),
                                 true,
                                 vertices->getCenter(),
                                 vertices->create(),
                                 indices.create(),
                                 1,
                                 1,
                                 color,
                                 NULL, // colors
                                 0, // colorsIntensity
                                 false);
```

**Comment by DiegoGomezDeck** [comment]
Hello Han,

Glob3-Mobile works on top of OpenGL ES 2.0 (and WebGL in HTML5).  OpenGL ES 2.0 doesn't support render of antialiased lines (nor points).

Let me know what are your specific needs to evaluate the options to follow.

-- Diego

**Comment by hanchao** [comment]
I try to support vector tile map on Glob3-Mobile. like [vtm](http://www.opensciencemap.org/)
Anti-aliasing on the road looks more beautiful
![image](https://f.cloud.github.com/assets/1942091/2156708/d194d91e-9464-11e3-91fe-be8c7c4445d2.png)

**Comment by hjanetzek** [comment]
Hi,  antialiasing in 3D is a bit more complicated than with 2.5D. I would suggest to read up on
http://cesiumjs.org/2013/04/22/Robust-Polyline-Rendering-with-WebGL/
and 'OpenGL Insights' book chapter 11, sample source code is available at
https://github.com/OpenGLInsights/OpenGLInsightsCode/tree/master/Chapter%2011%20Antialiased%20Volumetric%20Lines%20Using%20Shader-Based%20Extrusion

**Comment by hanchao** [comment]
Thanks.I am looking for opengl 2.0 antialiasing information

**Comment by DiegoGomezDeck** [comment]
Hello Han,

For this case, you have 2 options:

1) If your data set is not too big, you can use the the rasterization stuff included in g3m.  Take a look to the example at SymbologyActivity.java
2) If your data set is big, you can rasterize it on server side and consume the tiles-bitmaps with WMSLayer or URLTemplateLayer.

**Comment by gdp12315** [comment]
你好 han chao----- 原文 ----- 发件人: Han Chao 主　题: Re: [g3m] How can I render antialiasing line? (#55)时　间: 2014年2月28日  10:07:30I try to support vector tile map on Glob3-Mobile. see vtm
Anti-aliasing on the road looks more beautiful
