### ISSUE TITLE
example usage for WMSBilElevationDataProvider in WebGL / GWT?

### ISSUE THREAD

**Issue by akosmaroy** [glob3mobile/g3m#56]
I wonder if there is a sample to show how to use a WMSBilElevationProvider for G3M, when using it in a WebGL / GWT context?

the best would be if there is an example which point to an otherwise available elevation data service. if not, an example that shows how to set up our own WMS elevation data service using GeoServer or similar systems would also be nice

alternatively, how would one use SingleBilElevationDataProvider object in a WebGL conext?

**Comment by DiegoGomezDeck** [comment]
Hi Akos,

WMSBilElevationProvider is mostly abandoned code.  I pretty sure it doesn't work.

BTW, you can use SingleBilElevationDataProvider with an URL() pointing to "http://" instead of "file://"

**Comment by akosmaroy** [comment]
works fine as described above - thank you!

**Comment by nagydani** [comment]
Hi Diego,
It seems like SingleBilElevationDataProvider never discards the elevation map it has once loaded. Is there an ElevationDataProvider that intelligently loads and discards elevation data tiles just like texture tile providers do?
