### ISSUE TITLE
about documentation

### ISSUE THREAD

**Issue by hanchao** [glob3mobile/g3m#57]
Hi, Where can I find api documentation or tutorials?

**Comment by mdelacalle** [comment]
Hello!
First of all thank you for using the G3M framework, we will try help you.
Documentation:
We'd like to have more technical documents, we are working on it, but at the moment you have different possibilities:
- The demo project (in all platforms) has been though to see how to develop an application using the API. Please take a look, probably you will solve a lot of doubts working with:
  
  a) https://github.com/glob3mobile/g3m/tree/purgatory/Android/G3MAndroidDemo
  b) https://github.com/glob3mobile/g3m/tree/purgatory/iOS/G3MiOSDemo
  c) https://github.com/glob3mobile/g3m/tree/purgatory/WebGL/G3MWebGLDemo
- Some repositories, with example apps done developed with our SDK.
  
  a) https://github.com/glob3mobile/g3m-code-examples
  b) https://github.com/glob3mobile/g3m-rumsey
  c) https://github.com/glob3mobile/g3m_owm
- The wiki pages (This pages are not completed, but can helps you at the beginning)
  
  a) https://github.com/glob3mobile/g3m/wiki
- The issue list. If you have concrete doubts we will response ASAP, and most of the times, if you find bugs (thanks for testing), we fix it in hours.
- Contracting us, we offer professional services and if you have not the skills or simply don't want to know how maybe will be cheaper talk with us.

Thank you,

**Comment by hanchao** [comment]
Thank you very much

**Comment by machanguillo** [comment]
There is also several old tutorials in this link:
http://serdis.dis.ulpgc.es/~atrujill/glob3m/Tutorial/
They have been done with previous versions, but could give you an idea about how to use some of the basic methods.

**Comment by hanchao** [comment]
@machanguillo  Thank you.  That is what I want, so cool.
