### ISSUE TITLE
g3mWidget.setCameraPosition() doesn't work with low altitudes

### ISSUE THREAD

**Issue by akosmaroy** [glob3mobile/g3m#58]
G3MWidget's setCameraPosition() doesn't work with low altitude values, like 0 or 1 meters. in these cases, the camera setting operation is silently ignored.

Can you please make sure the camera position is set for these values as well? please also note that even negative altitude values are valid, e.g. some land is below sea level and below the WGS84 geoid model 0 level as well

**Comment by akosmaroy** [comment]
(note: I encountered this issue on Android)

**Comment by DiegoGomezDeck** [comment]
Hello Akos,

The default CameraConstrainer is SimpleCameraConstrainer.   In SimpleCameraConstrainer::onCameraChange you can find the default implementation (and the minHeight set to 10 meters).

For your case, I recommend you to implement a new CameraConstrainer based on your specific needs for the camera movement.

BTW, if you prefer I can expand SimpleCameraConstrainer to make configurable the minHeight.

**Comment by akosmaroy** [comment]
maybe in our case we can just remove the camera constrainer in general? is that possible?

**Comment by akosmaroy** [comment]
BTW, this is probably the same as https://github.com/glob3mobile/g3m/issues/23
