### ISSUE TITLE
Change opacity

### ISSUE THREAD

**Issue by ebrehault** [glob3mobile/g3m#6]
When we display a WMS layer on top of another one, by default the opacity is 1, so the user only see the top layer. Is it possible to change this opacity so users can see the base layer in transparency ?

**Comment by DiegoGomezDeck** [comment]
G3M doesn't support mixing of layers with transparency, I recommend to merge the layers on the server side.

**Comment by mdelacalle** [comment]
Currently we don't support that capability because of performance. Probably in the next future we are going to add that, if you need urgently that please contact with us we can give you the workaround or  our change our roadmap if was needed.

**Comment by DiegoGomezDeck** [comment]
If the WMS server support generation of PNGs with alpha channel (with a parameter such opacity or transparency) you can send this parameter using the method WMSLayer.setExtraParameter(string).   The current version _does_ support to mix layers respecting the alpha channel present in the PNGs.

**Comment by DiegoGomezDeck** [comment]
Add, to Layer class, float _transparency instance variable, and use it as an alpha factor when merging layers.

**Comment by NidhalSNSdev** [comment]
Can you give us more details to implement this solution

**Comment by mdelacalle** [comment]
Work in progress. I hope in a few time we will have this capability available

**Comment by amazingsmash** [comment]
Now Layers have an extra parameter (optional) that sets their transparency [0..1] when merging with other layers. G3MiOSDemo has an example where Spain is shown as a mix of BlueMarble layer and PNOA layer with a transparency of 0.5.

**Comment by mdelacalle** [comment]
great!

**Comment by mdelacalle** [comment]
https://github.com/glob3mobile/g3m_owm/blob/master/Shared/g3m_owm_shared/src/com/glob3mobile/g3mowm/shared/data/SimpleRasterLayerBuilder.java

![device-2013-12-26-141612](https://f.cloud.github.com/assets/233131/1810676/04d673d8-6e30-11e3-9768-4eeeae52ac0d.png)
