### ISSUE TITLE
JavaDesktopDemo contains merge conflicts in purgatory

### ISSUE THREAD

**Issue by akosmaroy** [glob3mobile/g3m#60]
both BatchBsonParser and BatchJsonParser sources fontain unresolved merge conflict artifacts, and thus are not compiling

**Comment by DiegoGomezDeck** [comment]
This project is dead code too, you're a master finding zombies! I'll call you "zombies killer".

I'll clean up it, thank you for reporting.

**Comment by DiegoGomezDeck** [comment]
Already removed in 'purgatory' branch.  One zombie less.
