### ISSUE TITLE
feature request: java desktop G3MWidget for fast development cycle?

### ISSUE THREAD

**Issue by akosmaroy** [glob3mobile/g3m#61]
I wonder how difficult it would be to create a 'java destop' G3MWidget, which could provide a very fast development cycle, as the compiled app wouldn't have to be downloaded to an Android / iOS device, or re-compiled with the GWT compiler each time?

**Comment by DiegoGomezDeck** [comment]
Hello Akos,

I didn't take the time to make a complete estimation, but taking in mind we already have 2 Java-based ports, I guess +/- a couple of weeks of work could be enough.

**Comment by hjanetzek** [comment]
I can recommend to use libgdx which provides a nice simple OpenGL setup and backends for desktop (with hazzle free inclusion of native opengl libs), android, gwt and also supports compilation of java back to iOS :)

 I've used libgdx to run my android code on desktop for the same reason - speed up testing cycles
