### ISSUE TITLE
Can i use google/bing maps and shapefiles with g3m?

### ISSUE THREAD

**Issue by ssppgit** [glob3mobile/g3m#62]
Hi guys!

I have found this library today and i want to know if it's possible to use maps from google maps or bing with this library of if i need a own server maps.

I also know if i can load shapefiles with this library

Thanks!

**Comment by mdelacalle** [comment]
Hello, thanks for using Glob3 Mobile.

1) Raster layer -> wichever, but pay attention with license issues. In the demo you have in that class a lot of examples about how to add new layers  

For example, on android:
https://github.com/glob3mobile/g3m/blob/purgatory/Android/G3MAndroidDemo/src/org/glob3/mobile/demo/SimplestRasterActivity.java
https://github.com/glob3mobile/g3m/blob/purgatory/Android/G3MAndroidDemo/src/org/glob3/mobile/demo/SimpleRasterLayerBuilder.java

2) Shapefiles:
Several optionsn:
a) rasterize in server (WMS)
b) transform to geojson
An example of this option is also in the demo.

https://github.com/glob3mobile/g3m/blob/purgatory/Android/G3MAndroidDemo/src/org/glob3/mobile/demo/SymbologyActivity.java

On this class is loaded a terrain model, vectorial data and a different base layer. If you want to see the demo working

https://play.google.com/store/apps/details?id=org.glob3.mobile.demo
https://itunes.apple.com/es/app/g3m/id601442573?mt=8#

thank you!
