### ISSUE TITLE
camera heading reset on position change

### ISSUE THREAD

**Issue by akosmaroy** [glob3mobile/g3m#63]
because the Camera::setGeodeticPosition() function also sets pitch:

```
void Camera::setGeodeticPosition(const Geodetic3D& g3d) {
  const Angle heading = getHeading();
  const Angle pitch = getPitch();
  setPitch(Angle::fromDegrees(-90));
  MutableMatrix44D dragMatrix = _planet->drag(getGeodeticPosition(), g3d);
  if (dragMatrix.isValid()) applyTransform(dragMatrix);
  setHeading(heading);
  setPitch(pitch);
}
```

for this reason, the camera jiggles when setting the position

our suggestion is to add the following function as well:

```
void Camera::setGeodeticPositionStablePitch(const Geodetic3D& g3d) {
  MutableMatrix44D dragMatrix = _planet->drag(getGeodeticPosition(), g3d);
  if (dragMatrix.isValid()) applyTransform(dragMatrix);
}
```

**Comment by akosmaroy** [comment]
see this commit: https://github.com/glob3mobile/g3m/commit/6d3e0ba232484a92df7b9852ca877fde600a78c2

as a humble try to add this function. I wonder if the corresponding Java call will be re-generated by a jenkins job :)

**Comment by akosmaroy** [comment]
see also: https://github.com/glob3mobile/g3m/commit/8087f938f8fce546a1a85dbed3d8d7ac062488af  (the previous commit was incomplete)

**Comment by DiegoGomezDeck** [comment]
Akos, I just run the conversion tool and you already have your changes available in Java side.
