### ISSUE TITLE
Can g3m use Multitexturing ？

### ISSUE THREAD

**Issue by EtachGu** [glob3mobile/g3m#64]

**Comment by DiegoGomezDeck** [comment]
Hello,

If by "Multitexturing" you mean multiple-raster-layers... the answer is yes.  You have to add more than one Layer to the LayerSet.

In the android sample application, you can see the example named "CartoDB Meteorites".  In this example, 2 layers are used at the same time.

**Comment by gdp12315** [comment]
thank you！
But i want to know ,which one of the methods is faster,if we use the OpenGL ES Multitextturing technology？----- 原文 ----- 发件人: Diego Gomez Deck 主　题: Re: [g3m] Can g3m use Multitexturing ？ (#64)时　间: 2014年3月31日  2:23:51Hello,

If by "Multitexturing" you mean multiple-raster-layers... the answer is yes.  You have to add more than one Layer to the LayerSet.

In the android sample application, you can see the example named "CartoDB Meteorites".  In this example, 2 layers are used at the same time.

**Comment by DiegoGomezDeck** [comment]
Hello @gdp12315 

In the current version, G3M does not use OpenGL multitexturing for layers mixing. The strategy we followed is to mix the bitmaps on CPU-side, and upload just one "composed" texture to the GPU.  We choose this strategy based on the goal to optimize the use of the limited resources (in this case GPU memory).

BTW, we try to avoid mixing layers in the app-side as much as posible and we always try to mix them on server-side (for example using a WMS server).   Using this approach, you don't download N bitmaps from internet and the (relative slow) mixing code doesn't happen on the mobile side, so less traffic data and less CPU use on mobile -> more battery time.

**Comment by gdp12315** [comment]
hi Diego Gomez Deck
It's very kind of you , Thank you so much !
I have a test and I find that "composed " texture really use less memory than OpenGL multitexturing .----- 原文 ----- 发件人: Diego Gomez Deck 主　题: Re: [g3m] Can g3m use Multitexturing ？ (#64)时　间: 2014年4月3日  2:21:18抄　送: gdp12315,  Hello @gdp12315 

In the current version, G3M does not use OpenGL multitexturing for layers mixing. The strategy we followed is to mix the bitmaps on CPU-side, and upload just one "composed" texture to the GPU.  We choose this strategy based on the goal to use the little resources (in this case GPU memory).

BTW, we try to avoid mixing layers in the app-side as much as posible and we always try to mix them on server-side (for example using a WMS server).   Using this approach, you don't download N bitmaps from internet and the (relative slow) mixing code doesn't happen on the mobile side, so less traffic data and less CPU use on mobile -> more battery time.
