### ISSUE TITLE
iOS Simulator Building Problems

### ISSUE THREAD

**Issue by milafrerichs** [glob3mobile/g3m#65]
Hello,
thanks for the project. I was trying to get a demo running since I want to integrate the library in a existing iOS App.
But I'm struggling to get it compiled for the simulator.
### The Problem

```
Undefined symbols for architecture i386:
  "std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::at(unsigned long) const", referenced from:
      ByteBufferBuilder::addStringZeroTerminated(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) in libPods.a(ByteBufferBuilder.o)
```

If you were wondering about the libPods.a:
I've build a CocoaPod spec to test out the building. 

https://github.com/milafrerichs/g3m_pod/blob/master/g3m.podspec

I added all the flags and so forth and the CocoaPods validator passed with a small edit and few warnings.
But the problem also exist if I just add the XCode Project file to another Project.
### Demos work

The Demos you provide work fine, so I was thinking this must be a configuration error.
Can you provide some more documentation/information about the Settings you use for the iOS Apps?
### Things I tried:

So far I've found the following:
The preprocessor has to have a definition for C_CODE:

```
GCC_PREPROCESSOR_DEFINITIONS' => 'C_CODE'
```

It depends on some frameworks:
'QuartzCore', 'CoreGraphics', 'CFNetwork', 'Foundation', 'GLKit', 'Security'

There seem to be some more configuration changes in your Demo Projects but I could not find the one that would solve the problem.

I was hoping you could help?
Thanks.

**Comment by DiegoGomezDeck** [comment]
Hello Mila,

Thank you very much for your detailed report.

BTW, I can't see what the problem is... may be you can send us a sample .xcode project?

In any case, We'll write soon a document with the project configuration setting for compiling g3m.

**Comment by milafrerichs** [comment]
Thanks for the quick reply @DiegoGomezDeck 
I added the Test Project here: https://github.com/milafrerichs/g3m_test

The problem is that I can't get the project to build. 
The build fails with the above error.
Since there is no precompiled Library I have to compile the G3MSDK myself wich leads to build errors. 
Hence I can't use your cool library.

If I can help writing the docs just ping me. I will definitely use this library :)

**Comment by DiegoGomezDeck** [comment]
Mila, can you send me your email address to "diego at consultar.com"? Or add me to skype, my nickname is DiegoGomezDeck
