### ISSUE TITLE
MarkRenderer fails to render marks depending on camera altitude

### ISSUE THREAD

**Issue by ztreer** [glob3mobile/g3m#67]
We've encountered the following bug:

Whenever the camera altitude goes below the altitude of the mark, the mark simply disappears!

We use the following code to create the mark:

```
    Geodetic3D pos = new Geodetic3D(G3MUtil.getGeodetic2D(navaid), SIMPLE_MARK_ALTITUDE + SIMPLE_MARK_OFFSET);
    Mark mark = new Mark(navaid.getIdent(), pos, AltitudeMode.RELATIVE_TO_GROUND);
```

(altitude results to 1100.0 meters)

created mark is passed to a MarksRenderer

By moving the camera, and descending below the mark's altitude the mark disappears completely.

**Comment by DiegoGomezDeck** [comment]
Hello,

Can you send me the position of the mark, as well as the camera position(*) when this bug happens?

(*) If you makes a long-press on the ground, the actual camera position (including the angles) are printed in the application log with a message like this:
Info: Camera position=(lat=25.74346747299569671d, lon=-5.3656762990500501687d, height=1664155.1381164724007) heading=-0.145718 pitch=-52.117699

**Comment by ztreer** [comment]
Sure, here it is:

04-01 17:35:15.092: I/Info:(14372): Touched on (Tile level=13, row=5323, column=4534, sector=(Sector (lat=47.368594345213374d, lon=19.248046875d) - (lat=47.39834920035925d, lon=19.2919921875d)))
04-01 17:35:15.092: I/Info:(14372): Camera position=(lat=47.370831503730905d, lon=19.241960307926195d, height=983.8113967274949) heading=-24.635599 pitch=-14.266462

**Comment by DiegoGomezDeck** [comment]
And the position of the mark?

**Comment by ztreer** [comment]
One of the marks is at :
lat: 47.4369010925
lon: 19.2555999756
altitude 1100.0

update: this altitude is using AltitudeMode.RELATIVE_TO_GROUND, i'm not sure how to get the resulting absolute altitude from that...

**Comment by ztreer** [comment]
At this point the mark still showed up :
04-01 17:39:55.037: I/Info:(14372): Camera position=(lat=47.366761212727184d, lon=19.234906652084955d, _height=1123.1236298941765_) heading=-26.023631 pitch=-14.269457

At this point it didn't:
04-01 17:40:12.332: I/Info:(14372): Camera position=(lat=47.368591718752825d, lon=19.235391601468937d, _height=1012.2891273516489_) heading=-27.256324 pitch=-14.263666

It very much seems like it switches when we reach the 1100.0 alt of the mark.

~~However it may not be the exact rule, as i can reproduce the scenario where multiple marks close to each other, viewed from the appropriate angle, and slowly moving the camera, are not disappearing at _exactly_ the same moment. I suspect we have to take the camera pitch angle (relative to ground), and the distance to the mark into account here.~~
This was cause by AltitudeMode.RELATIVE_TO_GROUND causing small differences in actual altitude.

**Comment by ztreer** [comment]
I repeated with using AltitudeMode.ABSOLUTE, the effect of the marks disappearing is still there.

Camera pos right after it disappeared:
04-01 17:49:52.887: I/Info:(15693): Touched on (Tile level=13, row=5324, column=4534, sector=(Sector (lat=47.39834920035925d, lon=19.248046875d) - (lat=47.42808726171426d, lon=19.2919921875d)))
04-01 17:49:52.887: I/Info:(15693): Camera position=(lat=47.3665119223405d, lon=19.251949160207758d, height=1076.892613024946) heading=-5.714247 pitch=-5.297620

**Comment by DiegoGomezDeck** [comment]
Hi @ztreer 

I can't reproduce the bug.   Using this code:

  Mark\* buggyMark = new Mark("BUGGY MARK",
                             Geodetic3D::fromDegrees(47.4369010925, 19.2555999756, 1100.0),
                             ABSOLUTE,
                             0 // minDistanceToCamera=4.5e+06,
                             );

  marksRenderer->addMark(buggyMark);

and:

  [[self G3MWidget] widget]->setAnimatedCameraPosition(TimeInterval::fromSeconds(5),
                                                       Geodetic3D::fromDegrees(47.3665119223405,
                                                                               19.251949160207758,
                                                                               1076.892613024946),
                                                       Angle::fromDegrees(-5.714247),
                                                       Angle::fromDegrees(-5.297620));

I got this screenshot:

![photo](https://cloud.githubusercontent.com/assets/1429156/2581929/0bc6bc6e-b9be-11e3-9eeb-cc02707d4f0e.PNG)

**Comment by ztreer** [comment]
This may be an android specific issue then, as we use the android sdk?

We've made a minimalistic android app, just showing how the 'buggy mark' disappears, using the code snippets that worked for you, but we still experience the mark disappearing.

Here is the full activity code:

```

package com.example.marktester;

import org.glob3.mobile.generated.AltitudeMode;
import org.glob3.mobile.generated.Angle;
import org.glob3.mobile.generated.G3MContext;
import org.glob3.mobile.generated.GTask;
import org.glob3.mobile.generated.Geodetic3D;
import org.glob3.mobile.generated.IThreadUtils;
import org.glob3.mobile.generated.LayerSet;
import org.glob3.mobile.generated.MapBoxLayer;
import org.glob3.mobile.generated.Mark;
import org.glob3.mobile.generated.MarksRenderer;
import org.glob3.mobile.generated.Quality;
import org.glob3.mobile.generated.TimeInterval;
import org.glob3.mobile.specific.G3MBuilder_Android;
import org.glob3.mobile.specific.G3MWidget_Android;

import android.app.Activity;
import android.os.Bundle;
import android.view.WindowManager.LayoutParams;
import android.widget.LinearLayout;

public class MainActivity extends Activity {

    MarksRenderer markRenderer;
    private G3MWidget_Android g3mWidget;
    private IThreadUtils threadUtils;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        getWindow().addFlags(LayoutParams.FLAG_KEEP_SCREEN_ON);

        LayerSet layerSet = new LayerSet();

        final MapBoxLayer mboxTerrainLayer = new MapBoxLayer("examples.map-qogxobv1", TimeInterval.fromDays(30), true, 2);
        mboxTerrainLayer.setTitle("Map Box Terrain");
        mboxTerrainLayer.setEnable(true);
        layerSet.addLayer(mboxTerrainLayer);


        final G3MBuilder_Android builder = new G3MBuilder_Android(this);


        builder.getPlanetRendererBuilder().setLayerSet(layerSet);
        builder.getPlanetRendererBuilder().setQuality(Quality.QUALITY_HIGH);
        builder.getPlanetRendererBuilder().setRenderDebug(true);

        markRenderer = new MarksRenderer(false);

        Mark buggyMark = new Mark("BUGGY MARK", 
                Geodetic3D.fromDegrees(47.4369010925, 19.2555999756, 1100.0), 
                AltitudeMode.ABSOLUTE, 
                0 // minDistanceToCamera=4.5e+06,
                );

        markRenderer.addMark(buggyMark);
        builder.addRenderer(markRenderer);

        g3mWidget = builder.createWidget();        
        g3mWidget.setBackgroundColor(android.graphics.Color.TRANSPARENT);        
        g3mWidget.getG3MWidget().getPlanetRenderer().setRenderTileMeshes(false);        
        threadUtils = g3mWidget.getG3MWidget().getG3MContext().getThreadUtils();

        final LinearLayout layout = (LinearLayout) findViewById(R.id.glob3);
        layout.addView(g3mWidget);

        threadUtils.invokeInRendererThread(
                new GTask() {
                    @Override
                    public void run(G3MContext context) {
                        g3mWidget.getG3MWidget().getPlanetRenderer().setRenderTileMeshes(true);
                        markRenderer.setEnable(true);
                        g3mWidget.getG3MWidget().setAnimatedCameraPosition(TimeInterval.fromSeconds(30),
                                Geodetic3D.fromDegrees(47.3665119223405,
                                19.251949160207758,
                                1076.892613024946),
                                Angle.fromDegrees(-5.714247),
                                Angle.fromDegrees(-5.297620));

                    }
                }, true);

    }

}

```

Note that i increased the animation time to 30 secs, also because of the camera movement the mark is not always in the viewport, but at the very end of the animation it could be seen disappearing. Moving the camera manually may show more of the effect.

An example camera position, where the mark has just disappeared (at altitude 1088m):

```
04-01 19:35:34.247: I/Info:(26731): Touched on (Tile level=15, row=21302, column=18136, sector=(Sector (lat=47.44294999517949d, lon=19.248046875d) - (lat=47.45037978769005d, lon=19.259033203124996d)))
04-01 19:35:34.252: I/Info:(26731): Camera position=(lat=47.390873880901545d, lon=19.244926350649056d, height=1088.987045511096) heading=-7.781512 pitch=-5.300741
```

I can send you the whole android project in a zip file if that helps you to reproduce the issue.

Thank you!

**Comment by DiegoGomezDeck** [comment]
yes, please send me the .zip to "diego (at) consultar.com"

**Comment by ztreer** [comment]
Email sent. 

fyi: the device we used for testing is a Samsung Galaxy Note 10.1 tablet (SM-P600), running android 4.3

**Comment by ztreer** [comment]
Important update!

The issue seems to be device specific!

I quickly deployed the same tester code to another android device (Samsung Note 2 - GT-N7100, android 4.3), and surprisingly it worked as expected, marks did not disappear at all.

This makes reproducing the issue much harder :(

**Comment by DiegoGomezDeck** [comment]
I tested on Kindle Fire HD and it works fine.  This bug will be difficult to catch!!! :(

**Comment by DiegoGomezDeck** [comment]
@ztreer may be you can put a breakpoint on Mark::render() to see which condition fail?

**Comment by ztreer** [comment]
Quite bizarre happenings - here is my theory:
- in the end occludedByHorizon becomes true in Mark.render(), this causes skipping the render
- it seems that it is caused by an erroneus cameraHeight (1374.0) which is not the actual camera height (840.9) - because it is clear that camera is _below_ the mark at this point, so the 1374.0 is clearly a wrong value, probably stuck there, and failed to update properly after (?)
- therefore the condition of  if (_position._height > cameraHeight) will go to the wrong conditional branch
- and tries to calculate horizon occlusion with the wrong method, which gives wrong results

Debugging screens:

![image](https://cloud.githubusercontent.com/assets/6747108/2590880/08026712-ba64-11e3-8769-4399573c14b0.png)

![image](https://cloud.githubusercontent.com/assets/6747108/2590883/0e271ea8-ba64-11e3-9013-7704911e4789.png)

**Comment by ztreer** [comment]
In fact if i change

```
  public final int getHeight()
  {
     return _height;
  }
```

to 

```
  public final int getHeight()
  {
     return (int) getGeodeticPosition()._height;
  }
```

in org.glob3.mobile.generated.Camera 

then the mark does not disappear...

It is a little confusing why an integer is used here - which becomes a double again in Mark.render(), also this doesn't seem like a consistent fix (as _height still can hold outdated values, which could be used in other methods), but maybe this takes us closer to the real solution.

The real disturbing stuff is how could this occur in a device-dependent way?

**Comment by DiegoGomezDeck** [comment]
Hello @ztreer 

Thank you very much for you hard work to hunt this resilient bug. 

Actually the problem is originated in a bad (very bad) naming in Camera class... let me explain it.

In camera, _widht / _height / getWidth() and getHeight() are related to the viewport dimensions of the camera.  I changed the names (to getViewPortHeight()) and fixed the wrong code in MarksRenderer (and in the process, I fixed another similar bug!)

I just pushed the new fixed version to 'purgatory' branch.

Can you give it a try?

**Comment by DiegoGomezDeck** [comment]
> The real disturbing stuff is how could this occur in a device-dependent way?

MarksRenderer was using getHeight() as if it was the geodetic-heigth in meters of the camera but in fact it was the pixels-height of the opengl viewport.   In different devices, we had different (pixel) heights.

**Comment by ztreer** [comment]
So the real difference between the devices was only the screen resolution after all :)

I've tried your fix, and now the issue seems to be gone, the marks do not disappear, thank you very much!

**Comment by DiegoGomezDeck** [comment]
Bug hunted!!!!
