### ISSUE TITLE
How can I add a sky to the globe ?

### ISSUE THREAD

**Issue by EtachGu** [glob3mobile/g3m#68]
hello Diego
I want to add a sky to the globe ,  just like the Google earth , I  don't how to make it 
Could you help me ? Thanks in advance:-)

**Comment by DiegoGomezDeck** [comment]
Hello @EtachGu 

Actually G3M doesn't have sky-effects.  The only "sky" parameter you can change in the current version is the backgroundColor.  For instance:

```
  builder.setBackgroundColor(Color.cyan().darker());
```

**Comment by gdp12315** [comment]
Thank you so much , 
I add a new renderer to draw the "Sky"----- 原文 ----- 发件人: Diego Gomez Deck 主　题: Re: [g3m] How can I add a sky to the globe ? (#68)时　间: 2014年4月10日  23:29:37Hello @EtachGu 

Actually G3M doesn't have sky-effects.  The only "sky" parameter you can change in the current version is the backgroundColor.  For instance:

  builder.setBackgroundColor(Color.cyan().darker());

**Comment by mdelacalle** [comment]
Could you put a screenshot with your sky???

Thanks!!

**Comment by gdp12315** [comment]
----- 原文 ----- 发件人: mdelacalle 主　题: Re: [g3m] How can I add a sky to the globe ? (#68)时　间: 2014年4月11日  13:38:10抄　送: gdp12315, &nbsp;Could you put a screenshot with your sky???

Thanks!!

El 11/04/2014, a las 05:23, gdp12315 &lt;notifications@github.com&gt; escribió:

&gt; Thank you so much , 

&gt; I add a new renderer to draw the "Sky"----- 原文 ----- 发件人: Diego Gomez Deck 主　题: Re: [g3m] How can I add a sky to the globe ? (#68)时　间: 2014年4月10日 23:29:37Hello @EtachGu 

&gt; 

&gt; Actually G3M doesn't have sky-effects. The only "sky" parameter you can change in the current version is the backgroundColor. For instance:

&gt; 

&gt; builder.setBackgroundColor(Color.cyan().darker());

&gt; 

&gt; 

&gt; —Reply to this email directly or view it on GitHub.

&gt; —

&gt; Reply to this email directly or view it on GitHub.

&gt;
