### ISSUE TITLE
Vector tiles

### ISSUE THREAD

**Issue by hanchao** [glob3mobile/g3m#70]
Any progress (or roadmap) on Vector tiles?

http://wiki.openstreetmap.org/wiki/Vector_tiles
Here are two formats, geojson and mvt
http://openstreetmap.us/~migurski/vector-datasource/

**Comment by DiegoGomezDeck** [comment]
Hello @hanchao 

We're working on it just now, we'll publish really soon support for consuming/rasterizing vector tiles.

**Comment by DiegoGomezDeck** [comment]
@hanchao 

If you keep interested on this, please take a look to https://github.com/glob3mobile/mmt-vector-tiles (a tool to generate tile-vectors) and (for g3m side) see the changes on branch 'rasterizer-refactor'

In the short future, the changes in 'rasterizer-refactor' will be merged on 'purgatory' branch, but meanwhile I'd love to have some feedback.

**Comment by hanchao** [comment]
I've tried it (`rasterizer-refactor`). Very cool. 

The map look a little fuzzy, raster and vector both 

![image](https://raw.githubusercontent.com/hanchao/hanchao.github.io/master/pic/g3m_vector_tiles.png)

**Comment by DiegoGomezDeck** [comment]
Hello @hanchao 

I can't see the attached png. Can you, please, upload it again?

**Comment by DiegoGomezDeck** [comment]
It looks like maxLevel (of the visible layers) is too low, please try with bigger values for maxLevel.
