### ISSUE TITLE
need performance improvements on android

### ISSUE THREAD

**Issue by akosmaroy** [glob3mobile/g3m#72]
G3M would benefit greatly from increased performance improvements on Android. for a generic performance profile, it is clear that most time is spent in Tile.isVisible, see the following profile screenshot from eclipse:

![with_ground_chart](https://cloud.githubusercontent.com/assets/333140/2845400/d027fdb4-d095-11e3-9517-ffd686a01bee.png)

now, the interseting thing is that the same profile exists when the ground chart is not shown, in which case none of these tiles would need to exist, as they are not visible:

![no_ground_chart](https://cloud.githubusercontent.com/assets/333140/2845407/dc933a14-d095-11e3-848c-9f0927b9bc43.png)

a simple improvement could be that generating these tiles is only done when the ground chart needs to be shown, for example consider the following dirty hack:

```
diff --git a/Commons/G3MSharedSDK/src/org/glob3/mobile/generated/PlanetRenderer.
index 5b1c385..57ad08a 100644
--- a/Commons/G3MSharedSDK/src/org/glob3/mobile/generated/PlanetRenderer.java
+++ b/Commons/G3MSharedSDK/src/org/glob3/mobile/generated/PlanetRenderer.java
@@ -457,7 +457,7 @@ public class PlanetRenderer extends DefaultRenderer implemen

     final double nowInMS = _lastSplitTimer.now().milliseconds(); //Getting now 

-    if (_firstRender && _tilesRenderParameters._forceFirstLevelTilesRenderOnSta
+    if (!_renderTileMeshes && _firstRender && _tilesRenderParameters._forceFirs
     {
       // force one render pass of the firstLevelTiles tiles to make the (toplev
       // loaded as they will be used as last-chance fallback texture for any ti
@@ -469,8 +469,7 @@ public class PlanetRenderer extends DefaultRenderer implemen
         tile.render(rc, _glState, null, planet, cameraNormalizedPosition, camer
       }
     }
-    else
-    {
+    else if (_renderTileMeshes ) {^M
       java.util.LinkedList<Tile> toVisit = new java.util.LinkedList<Tile>();
       for (int i = 0; i < firstLevelTilesCount; i++)
       {
```

thus by using Occam'r Razor, and not creating entities when not needed, a lot of performance improvements can be made

**Comment by DiegoGomezDeck** [comment]
Hello @akosmaroy 

Thank you for your very detailed issue report.

To _really_ remove the tiled-subsystem from the render loop, more things have to be done.  There are some other subsystems that depends on the tiling, for instance Mesh, Mark and Shape (when altitude mode is RELATIVE_TO_GROUND) depends on the current visible tiles for getting the height estimation of the terrain.  The same happens with VisibleSectorListener, the current implementation uses the current-visible tiles for the visible-sector calculation.

Probably there are more places with this dependencies, but I don't remember now.

BTW, the easiest way to remove the tiling is just removing the PlanetRenderer from the renderers list.  It can't be done using the current Builder (as it assumes the default case of a globe with the tiling).  May be you can create the widget without the PlanetRenderer "by hand" (using the builder code as reference), in this way we can detect all the places with dependencies to the tiles.

**Comment by akosmaroy** [comment]
removing the planet renderer sounds interesting.

the above limitations seem reasonable for us for the time being, as we generally know the elevation of everything we want to render, thus we won't use RELATIVE_TO_GROUND

we'll give it a go

OTOH I'd really suggest looking at this from another perspective: even if the tiles need to be created, if none of them are visible (as the ground chart is not shown), is there a reason that isVisible() is being called on them? should this always be false?

**Comment by akosmaroy** [comment]
looking at the PlanetRenderer.render() call, what I find interesting is that a lot of Tile objects are re-created (?), and thus their mesh is always being re-created, which seems to be expensive.

see the profile here: 
![tile_render](https://cloud.githubusercontent.com/assets/333140/2870639/48973d10-d2d4-11e3-8dea-1912f906fd96.png)

most of isVisible() is spent on creating a Mesh for the Tile. this might be due to the following code in PlanetRenderer.render():

```
    if (_firstRender && _tilesRenderParameters._forceFirstLevelTilesRenderOnStart)
    {
      // force one render pass of the firstLevelTiles tiles to make the (toplevel) textures
      // loaded as they will be used as last-chance fallback texture for any tile.
      _firstRender = false;

      for (int i = 0; i < firstLevelTilesCount; i++)
      {
        Tile tile = _firstLevelTiles.get(i);
        tile.render(rc, _glState, null, planet, cameraNormalizedPosition, cameraAngle2HorizonInRadians, cameraFrustumInModelCoordinates, _statistics, _verticalExaggeration, layerTilesRenderParameters, _texturizer, _tilesRenderParameters, _lastSplitTimer, _elevationDataProvider, _tessellator, _tileRasterizer, _layerSet, _renderedSector, _firstRender, _texturePriority, texWidthSquared, texHeightSquared, nowInMS, _renderTileMeshes, _logTilesPetitions, _tileRenderingListener); // if first render, force full render
      }
    }
    else
    {
      java.util.LinkedList<Tile> toVisit = new java.util.LinkedList<Tile>();
      for (int i = 0; i < firstLevelTilesCount; i++)
      {
        toVisit.addLast(_firstLevelTiles.get(i));
      }

      while (toVisit.size() > 0)
      {
        java.util.LinkedList<Tile> toVisitInNextIteration = new java.util.LinkedList<Tile>();

        for (java.util.Iterator<Tile> iter = toVisit.iterator(); iter.hasNext();)
        {
          Tile tile = iter.next();

          tile.render(rc, _glState, toVisitInNextIteration, planet, cameraNormalizedPosition, cameraAngle2HorizonInRadians, cameraFrustumInModelCoordinates, _statistics, _verticalExaggeration, layerTilesRenderParameters, _texturizer, _tilesRenderParameters, _lastSplitTimer, _elevationDataProvider, _tessellator, _tileRasterizer, _layerSet, _renderedSector, _firstRender, _texturePriority, texWidthSquared, texHeightSquared, nowInMS, _renderTileMeshes, _logTilesPetitions, _tileRenderingListener); //SENDING SQUARED TEX SIZE -  if first render, force full render
        }

        toVisit = toVisitInNextIteration;
      }
    }

```

as in the tile.render() call, the toVisitInNextIteration are subtiles always created fresh:

```
     else
      {
        java.util.ArrayList<Tile> subTiles = getSubTiles(layerTilesRenderParameters._mercator);
        if (_justCreatedSubtiles)
        {
          lastSplitTimer.start();
          tilesStatistics.computeSplitInFrame();
          _justCreatedSubtiles = false;
        }

        final int subTilesSize = subTiles.size();
        for (int i = 0; i < subTilesSize; i++)
        {
          Tile subTile = subTiles.get(i);
          toVisitInNextIteration.addLast(subTile);
        }
      }

```

as these are always new tiles, their Mesh is always newly created, which seems to take a lot of time

**Comment by DiegoGomezDeck** [comment]
Hello @akosmaroy 

Related to that:

> OTOH I'd really suggest looking at this from another perspective: even if the tiles need to be created, if none of them are visible (as the ground chart is not shown), is there a reason that isVisible() is being called on them? should this always be false?

The terrain-tiling system is a _virtual_ large quadtree that covers the whole world.  The isVisible() method (as well as meetsRenderCriteria()) are the 2 methods that allows us to have the smallest set of the complete quadtree instantiated.  The Tile::isVisible() method allows, for instante, to prune the quadtree when a subset of the large-virtual quadtree is not visible (see Tile::setIsVisible()).  Tile::isVisible(), in fact, test if any tile provides information for the current visible part of the earth and allows to keep just a small set of the _virtual_ complete quadtree.

What I'm trying to say is that isVisible() is not only about "real" visibility (in your case, the tile-meshes are not visible, but the tiles are) but it's more about if the tile makes senses to process in the current camera situation.  In the "normal" case, it's the very same... every visible tile will be rendered; that's the reason we test the visibility using the tile's mesh bounds.

The only improvement I see here is to avoid creating the tile-mesh just for visibility testing, but it becomes tricky to consider terrain-elevation (for example: a far away tile containing a high mountain) and the tile's skirts.

**Comment by DiegoGomezDeck** [comment]
@akosmaroy 

> looking at the PlanetRenderer.render() call, what I find interesting is that a lot of Tile objects are re-created (?), and thus their mesh is always being re-created, which seems to be expensive.

Not really.... see Tile::getSubTiles().  It's a lazy initialization.... the subtiles are created only the first time they're needed (and pruned when some ancestor parent becomes invisible).

And note that Tile::getTessellatorMesh() and _texturizedMesh are lazy initialized too.

**Comment by akosmaroy** [comment]
I see the lazy initialization approach. the interesting thing about the above case is that for the whole duration of the profile session, the camera is positioned int he very same position. and it just 'looks around'. moreover, the profiling session is started after this has been going on for a while - thus one would assume that all tiles 'in the vicinity' have been already created

maybe a better strategy for retaining tiles would reduce the number of new tiles (re)created?

**Comment by DiegoGomezDeck** [comment]
>  thus one would assume that all tiles 'in the vicinity' have been already created

Note that NOT all the needed tiles are created in a shot, we follow a "progressive" creation of the quadtree subset to avoid a bottleneck when a lot of tiles need to be created at the very same time.

We have a "time-budget" where some few tiles are created for each frame, see FrameTasksExecutor and FrameTask subclasses.  And the Tile::meetsRenderCriteria(), specifically:

  if (tilesRenderParameters->_useTilesSplitBudget) {
    if (_subtiles == NULL) { // the tile needs to create the subtiles
      if (lastSplitTimer->elapsedTimeInMilliseconds() < 67) {
        // there are not more time-budget to spend
        return true;
      }
    }
  }

I guess this is happening in your case.  I asume you start with a camera position very close to the ground, and with a camera pitch that points to the horizon.   Actually this is the worst case for the current tiling system, as it need from the very beginning to create (progressively) a lot of tiles.  Is this your case?

**Comment by DiegoGomezDeck** [comment]
> the profiling session is started after this has been going on for a while - thus one would assume that all tiles 'in the vicinity' have been already created

oops, I didn't read that part... so I'm not sure if my previous response makes sense.

**Comment by akosmaroy** [comment]
in my case, the camera position (including the elevation) is always the same. I'm looking 'around', that is, down, up, and rotating the camera in various directions. as said, the profiling session is started after this has been going on for while, in the hope that most of the tiles have already been created

**Comment by DiegoGomezDeck** [comment]
@akosmaroy if you're online, may be we can make a pair-profiling session to see exactly what it's happing in your case.

**Comment by akosmaroy** [comment]
let's do that

**Comment by akosmaroy** [comment]
as discussed, please extend the G3MWidget code so that it works without a PlanetRenderer

please also change G3MWidget_Builder so that it is easy to overwirte the following part in create() by subclassing or a similar method:

```
      mainRenderer = new CompositeRenderer();
      if (!containsPlanetRenderer(getRenderers()))
      {
        ((CompositeRenderer) mainRenderer).addRenderer(getPlanetRendererBuilder().create());
      }
      for (int i = 0; i < getRenderers().size(); i++)
      {
        ((CompositeRenderer) mainRenderer).addRenderer(getRenderers().get(i));
      }

```

or allow to manually remove / 'not add' a planet renderer

also let's investigate the possibility to maintain (not delete) Tiles from the PlanetRenderer for an extended period of time, esp. in the use case where the camera position does not change significantly, but the camera rotates around

**Comment by akosmaroy** [comment]
as we experimented with removing the planet renderer from the G3MWidgetBuilder, here are some measurements. please see the diff for the code against current purgatory below. the scenarios measured were:
- 'original state' with ground chart showing or not showing
- our own renderers grouped together by type + visual artifacts would not include transparency, with ground chart showing or not showing
- Planet renderer removed (no ground chart)

results in terms of frames per second:

| scenario | Samsung Tablet 10.1 | Google Glass |
| --- | --- | --- |
| original ground chart | 4 | < 1 |
| original no ground chart | 6 | < 1 |
| renderers grouped ground chart | 7 | 3 |
| renderers grouped no ground chart | 15 | 6 |
| PlanetRenderer removed | 37 | 14 |

in another test, I experimented with adding 1000 Marks and BoxShapes, and then removing them. this test was done after removing PlanetRenderer, and only on the Samsung Tablet. results:

| scenario | Samsung Tablet 10.1 |
| --- | --- |
| 1000 Marks & BoxShapes | 10 |
| none of these shapes | 70 |

the code change in g3m to remove PlanetRenderer:

```
diff --git a/Android/G3MAndroidSDK/src/org/glob3/mobile/specific/ES2Renderer.java b/Android/G3MAndroidSDK/src/org/glob3/mobile/specific/ES2Renderer.java
index 28e8b6d..8ec3dd1 100644
--- a/Android/G3MAndroidSDK/src/org/glob3/mobile/specific/ES2Renderer.java
+++ b/Android/G3MAndroidSDK/src/org/glob3/mobile/specific/ES2Renderer.java
@@ -11,6 +11,7 @@ import org.glob3.mobile.generated.GL;
 import android.opengl.GLES20;
 import android.opengl.GLSurfaceView;
 import android.os.Looper;
+import android.util.Log;


 //import org.glob3.mobile.generated.IGLProgramId;
@@ -84,6 +85,8 @@ public final class ES2Renderer
       else {
          _startTime = now;
       }
+      
+      Log.e("ES2Renderer", "render time: " + (timeElapsedInRender / 1000.f));

    }

diff --git a/Commons/G3MSharedSDK/src/org/glob3/mobile/generated/IG3MBuilder.java b/Commons/G3MSharedSDK/src/org/glob3/mobile/generated/IG3MBuilder.java
index 19fcf3e..4b92eaa 100644
--- a/Commons/G3MSharedSDK/src/org/glob3/mobile/generated/IG3MBuilder.java
+++ b/Commons/G3MSharedSDK/src/org/glob3/mobile/generated/IG3MBuilder.java
@@ -416,7 +416,7 @@ public abstract class IG3MBuilder
       mainRenderer = new CompositeRenderer();
       if (!containsPlanetRenderer(getRenderers()))
       {
-        ((CompositeRenderer) mainRenderer).addRenderer(getPlanetRendererBuilder().create());
+        //((CompositeRenderer) mainRenderer).addRenderer(getPlanetRendererBuilder().create());
       }
       for (int i = 0; i < getRenderers().size(); i++)
       {
diff --git a/Commons/G3MSharedSDK/src/org/glob3/mobile/generated/RenderedSectorCameraConstrainer.java b/Commons/G3MSharedSDK/src/org/glob3/mobile/generated/RenderedSectorCameraConstrainer.java
index d89e71f..62aa60d 100644
--- a/Commons/G3MSharedSDK/src/org/glob3/mobile/generated/RenderedSectorCameraConstrainer.java
+++ b/Commons/G3MSharedSDK/src/org/glob3/mobile/generated/RenderedSectorCameraConstrainer.java
@@ -17,7 +17,7 @@ public class RenderedSectorCameraConstrainer implements ICameraConstrainer

   public boolean onCameraChange(Planet planet, Camera previousCamera, Camera nextCamera)
   {
-    final Sector sector = _planetRenderer.getRenderedSector();
+   final Sector sector =  _planetRenderer == null ? Sector.fullSphere() : _planetRenderer.getRenderedSector();
     final Geodetic3D position = nextCamera.getGeodeticPosition();
     final boolean isValidHeight = (position._height <= _maxHeight);

diff --git a/Commons/G3MSharedSDK/src/org/glob3/mobile/generated/SimpleInitialCameraPositionProvider.java b/Commons/G3MSharedSDK/src/org/glob3/mobile/generated/SimpleInitialCameraPositionProvider.java
index 4a0020a..806e530 100644
--- a/Commons/G3MSharedSDK/src/org/glob3/mobile/generated/SimpleInitialCameraPositionProvider.java
+++ b/Commons/G3MSharedSDK/src/org/glob3/mobile/generated/SimpleInitialCameraPositionProvider.java
@@ -5,8 +5,8 @@ public class SimpleInitialCameraPositionProvider extends InitialCameraPositionPr

   public final Geodetic3D getCameraPosition(Planet planet, PlanetRenderer planetRenderer)
   {
-    final Sector sector = planetRenderer.getRenderedSector();
-    if (sector == null)
+   final Sector sector =  planetRenderer == null ? Sector.fullSphere() : planetRenderer.getRenderedSector();
+   if (sector == null)
     {
       return planet.getDefaultCameraPosition(Sector.fullSphere());
     }

```

**Comment by akosmaroy** [comment]
another significant improvement it seems is to remove the forces GC fromt he ES2Renderer. the rendering times measured are the following for us:

| scenario | rendering time in seconds |
| --- | --- |
| forced GC | 0.7 - 1.5 seconds |
| no forced GC | 0.04 seconds |

interestingly the FPS reported by ES2Renderer is about the same in both cases, but the forced GC started in the 'remaining time' seem to ruin the whole experience

an alternative approach would be to initiated a forced GC in a timely manner, say every 10 seconds or longer intervals only

the code snippet to achieve this is the following:

```
diff --git a/Android/G3MAndroidSDK/src/org/glob3/mobile/specific/ES2Renderer.java b/Android/G3MAndroidSDK/src/org/glob3/mobile/s
index 28e8b6d..013f17f 100644
--- a/Android/G3MAndroidSDK/src/org/glob3/mobile/specific/ES2Renderer.java
+++ b/Android/G3MAndroidSDK/src/org/glob3/mobile/specific/ES2Renderer.java
@@ -11,6 +11,7 @@ import org.glob3.mobile.generated.GL;
 import android.opengl.GLES20;
 import android.opengl.GLSurfaceView;
 import android.os.Looper;
+import android.util.Log;


 //import org.glob3.mobile.generated.IGLProgramId;
@@ -67,7 +68,7 @@ public final class ES2Renderer
       long timeElapsedInRender = now - _startTime;
       long timeLeftInMS = GOAL_MS_PER_FRAME - timeElapsedInRender;
       if (timeLeftInMS > 0) {
-         System.gc();
+         //System.gc();

          timeElapsedInRender = System.currentTimeMillis() - _startTime;
          timeLeftInMS = GOAL_MS_PER_FRAME - timeElapsedInRender;
@@ -84,6 +85,8 @@ public final class ES2Renderer
       else {
          _startTime = now;
       }
+      
+      Log.e("ES2Renderer", "render time: " + (timeElapsedInRender / 1000.f));

    }

```

**Comment by akosmaroy** [comment]
Diego,

And instead of removing the Planet Renderer, what would be your take on the following approach:

```
diff --git a/Commons/G3MSharedSDK/src/org/glob3/mobile/generated/PlanetRenderer.
index ed56e75..53cde00 100644
--- a/Commons/G3MSharedSDK/src/org/glob3/mobile/generated/PlanetRenderer.java
+++ b/Commons/G3MSharedSDK/src/org/glob3/mobile/generated/PlanetRenderer.java
@@ -419,6 +419,10 @@ public class PlanetRenderer extends DefaultRenderer impleme
   public final void render(G3MRenderContext rc, GLState glState)
   {

+      if (!isEnable()) {
+          return;
+      }
+  
     final LayerTilesRenderParameters layerTilesRenderParameters = getLayerTiles
     if (layerTilesRenderParameters == null)
     {
```

**Comment by DiegoGomezDeck** [comment]
Hello @akosmaroy,

Actually the test of isEnable() is already performed as CompositeRenderer::render(), so no need to change PlanetRenderer::render() to avoid render-process while disabled.

**Comment by DiegoGomezDeck** [comment]
@akosmaroy 

The rest of the changes are already done on my current branch, I'll be able to merge them into purgatory in a few days.  Anyway if you want to give them a try, see the 'rasterizer-refactor' branch
