### ISSUE TITLE
TerrainTouchListener  added by PlanetRenderer.addTerrainTouchListener does not receive events in WebGL

### ISSUE THREAD

**Issue by nagydani** [glob3mobile/g3m#74]
After having created a widget in the initializaion part of the WebGL application, I add a TerranTouchListener as follows:

``` java
widget = builder.createWidget(); // initialization ends here
widget.getG3MWidget().getPlanetRenderer().addTerrainTouchListener(myTerrainTouchListener);
```

Nonetheless, the **onTerrainTouch** method of **myTerrainTouchListener** never gets called. What am I doing wrong?

**Comment by nagydani** [comment]
Similary, no results from adding a **LayerTouchEventListener** to the displayed layer using **Layer.addLayerTouchEventListener**. Its **onTerrainTouch** method is similarly never called.

**Comment by DiegoGomezDeck** [comment]
Hello @nagydani 

Your code is ok.

I guess the misunderstanding comes from the fact that to fire this event you have to do a "long press" click (press and hold the finger for a while).  PlanetRenderer uses Long-Press to avoid event handling conflicts with the Camera events handlers.

**Comment by DiegoGomezDeck** [comment]
Forgot to say:  It's a long-press for mobile devices (iOS and Android), and right-click on HTML5.

**Comment by nagydani** [comment]
Hi Diego,

Thanks for the operative response! I knew about the long-press on mobile devices (that is how I tested it first), but did not know about right-click. Right-click works splendidly, thank you!

Then comes the next question: is it somehow possible to re-configure this behavior from within the application, without changing the library code? For example to use double-left-click instead of right-click for this purpose? Also, I would really like to use right press instead of shift + left press for rotations.

**Comment by DiegoGomezDeck** [comment]
G3M provides a pluggable design where almost everything can be changed.

In this case, CameraRenderer delegates the UI events to a collection of CameraEventHandler.  So, you can create different flavors of CameraEventHandler and plug them into the CameraRenderer replacing the defaults.
