### ISSUE TITLE
How to load lots of models

### ISSUE THREAD

**Issue by autowo** [glob3mobile/g3m#79]
Hi,
   When I want to load big meshes using "ShapesRenderer",the system is easy going to collapse. Is there any solution to load models by LOD strategies?
   I have many building models,each one is larger than 50MB etc.So,this method which using “Blender” and “json2bson,sh” is not very suitable for making json or bson .I'd suggest adopting “osgb” similar format to make the LOD.

**Comment by DiegoGomezDeck** [comment]
Hello @autowo 

For today, we have not support for auto-LOD of 3d-models.   BTW, it can be done... what are exactly your requirements?

**Comment by autowo** [comment]
Hi Diego,
I  hope  it can load 3D city models perfectly such as GoogleEarth or HereMaps.

**Comment by mdelacalle** [comment]
Hello @autowo.

You want load  3D city models as Google Earth or Here Maps…, great

Do you have the models?, which models?, formats?, sizes?, etc…
Where do you want to load the models? iOS, Android, webGL, Desktop Apps (all this options are valid with g3m)
This models, do you want to work offline with there, are you thinking in LoD?, ….

It’s very hard to come a solution without requirements, and load model as google earth it’s not a requirement.
You can load 3d Model perfectly with g3m , and you can develop very good apps with an excellent performance, multi-platform and free.

I hope to can help you but we need to know more to help you. 

If you have concrete issues with out library not hesitate to open new issues specifying what do you need.

Thanks for using g3m and I close the issue.
