### ISSUE TITLE
How to determine whether or not a Geodetic3D point is visible or not?

### ISSUE THREAD

**Issue by nagydani** [glob3mobile/g3m#82]
Determining the 2D projection coordinates of a Geodetic3D is, apparently, done in two steps:
- First, the Geodetic3D is converted to Vector3D of its cartesian coordinates.
- Then this Vector3D is fed into MutableMatrix44D.project() of the matrix corresponding to the camera that would calculate the respective 2D coordinates.

Note, that this method is somewhat numerically inaccurate, but with double precision it might be good enough.

However, project() would just as happily project points that are behind the camera, even though they are not visible. This is because it only checks whether the Z coordinate is zero, but not it sign. Is there any API to check that first?

**Comment by DiegoGomezDeck** [comment]
@nagydani 

There is a more "short" version for projecting cartesian coordinate to screen-pixels.  Take a look to Camera::point2pixel() methods.

About the Z-axis, we can expand the Matrix (and Camera) to include something like "::pointTo3DPixel" (or a much better name to come).

In fact, you can find the code to project AND calculating the Z-component commented-out in MutableMatrix44D::project() source code.
