### ISSUE TITLE
Streaming elevation data for the whole planet

### ISSUE THREAD

**Issue by isimonescu** [glob3mobile/g3m#84]
Hello,

congratulations on this project, you have a great 3d globe framework going on here.

I'm interested in making a 3d globe with elevation support for the whole planet. As I've read, the WMSBilElevationDataProvider seems deprecated (I tried to link it to a NASA WMS server and got an access violation elsewhere in code) and the SingleBilElevationDataProvider only seems to cover partial DEM files.

My question: will there be support for streaming any kind of elevation data? Can it be done by putting up an private DEM server? Or can I hack in to the code by using SingleBilElevationDataProvider additions dynamically?

Kinds regards,
Simon

**Comment by janusd** [comment]
What have you been up to, Simon? I'm really interested in a solution too!
Best regards, Janus

**Comment by DiegoGomezDeck** [comment]
See #91
