### ISSUE TITLE
Altitude cannot be less than 10?

### ISSUE THREAD

**Issue by DrakkLord** [glob3mobile/g3m#87]
Hi,

I'm having issues wit setting the altitude near or less than zero, I'm not using an elevation map, so I guess 0 is the mean sea level so negative altitude should be permitted, but the lowest I can go is 10 meters.

I've extended the Android demo app to demonstrate this issue you can get the project here : https://dl.dropboxusercontent.com/u/1025247/G3MAndroidDemo.zip

The 'Altitude Demo' button takes you into a demo where you drag up or down to change the altitude, it works as long as you stay away from zero, the HUD shows where you are at and where you are trying to be, it's obvious that no matter what you set you cant be lower than 10 meters.

Thanks,
   Adam

**Comment by DiegoGomezDeck** [comment]
Hello @DrakkLord 

Please take a look to SimpleCameraConstrainer.  It's the default camera constrainer put by the g3mbuilder.  You can replace it by a Constrainer written by you, or... better... expand this SimpleCameraConstrainer to receive minHeight/maxHeight by parameters in the constructor, and submit a pull-request.
