### ISSUE TITLE
issues when trying to compile for android using eclipse

### ISSUE THREAD

**Issue by akosmaroy** [glob3mobile/g3m#9]
Hi,

I'm trying to compile the sources available here on github for Android, using eclipse. It doesn't work 'out of the box', please see the issues outlined here. I'd appreciate guidance on how to 'properly' do this (as the README doesn't really provide a lot of details)

after cloning the repository, first I'm importing the G3MSharedSDK project into eclipse, as 'import existing project into workspace'. this seems to work fine.

then I'm importing G3MAndroidSDK as as 'import existing project into workspace'. so far no error reports from eclipse

then I'm importing G3MAndroidDemo as as 'import existing project into workspace'. here I'm getting the following error message from eclipse:

```
Description Resource    Path    Location    Type
The container 'Android Dependencies' references non existing library '/home/akos/src/glob3mobile/g3m/Android/G3MAndroidSDK/bin/g3mandroidsdk.jar'   G3MAndroidDemo      Build path  Build Path Problem
```

and indeed, the G3MAndroidSDK project did not build this jar from eclipse. moreover, I'm not seeing other build tool descriptions either, like maven, etc that would build this jar

I wonder how to proceed from here?

**Comment by mdelacalle** [comment]
Hello
You need to have in the same workspace the projects:

G3MAndroidSDK
G3MSharedSDK

and the demo project

G3MAndroidDemo

simply building and cleaning must work (you have to have installed properly the ADT and all the android stuff)

The problem that you describe if all is well done normally is resolved only cleaning

Thanks

**Comment by akosmaroy** [comment]
indeed, cleaning did solve the issue!
