### ISSUE TITLE
WMS overlay

### ISSUE THREAD

**Issue by DimitrisMarm** [glob3mobile/g3m#92]
Hi.

How can i put a wms as overlay with specific bbox on a map?

I use the android SDK.

**Comment by DiegoGomezDeck** [comment]
Hello @DimitrisMarm 

You can find an example at http://github.com/glob3mobile/g3m/blob/purgatory/Android/G3MAndroidDemo/src/org/glob3/mobile/demo/SimpleRasterLayerBuilder.java

Specifically

``` java
      final WMSLayer blueMarble = new WMSLayer("bmng200405", new URL("http://www.nasa.network.com/wms?", false),
               WMSServerVersion.WMS_1_1_0, Sector.fullSphere(), "image/jpeg", "EPSG:4326", "", false, new LevelTileCondition(0,
                        18), TimeInterval.fromDays(30), true);
```

**Comment by DimitrisMarm** [comment]
Hi @DiegoGomezDeck 

my code is based on this sample, but when i try to load a wms from my wms server it shows nothing, and in logCat i get this error (my mws version is 1.1.0)

Downloader_Android_Handler Error runWithDownloader: statusCode=0, url=http://localhost:8085/geoserver/wms?REQUEST=GetMap&SERVICE=WMS&VERSION=1.1.1&WIDTH=256&HEIGHT=256&BBOX=24.0,-90.0,50.0,-66.0&LAYERS=topp:states&FORMAT=image/png&SRS=EPSG:4326&STYLES=population&TRANSPARENT=TRUE

**Comment by mdelacalle** [comment]
It seems that the server is not responding properly.
If you put this url in browser, what is happening?
obviously I can’t see that because it’s a local URL , maybe you can try with a public server that you are sure that it’s working and after that try with your server.

Thanks!

**Comment by DimitrisMarm** [comment]
Hi @mdelacalle,

i have check my local wms server in a java desktop application where i have and it works fine.
is something else i have to do/check in my project or in my pc?

Thanks!

**Comment by DiegoGomezDeck** [comment]
> Downloader_Android_Handler Error runWithDownloader: statusCode=0, url=http://localhost:8085/geoserver/wms?REQUEST=GetMap&SERVICE=WMS&VERSION=1.1.1&WIDTH=256&HEIGHT=256&BBOX=24.0,-90.0,50.0,-66.0&LAYERS=topp:states&FORMAT=image/png&SRS=EPSG:4326&STYLES=population&TRANSPARENT=TRUE

'localhost' means the Android device itself. I don't think you're running the WMS server on the android device, so localhost is wrong.

One time you replace localhost with the server's IP, see is this URL works in a browser:

http://[_hereTheServerIP_]:8085/geoserver/wms?REQUEST=GetMap&SERVICE=WMS&VERSION=1.1.1&WIDTH=256&HEIGHT=256&BBOX=24.0,-90.0,50.0,-66.0&LAYERS=topp:states&FORMAT=image/png&SRS=EPSG:4326&STYLES=population&TRANSPARENT=TRUE

Things that could be wrong: WMS version, layer name, format, projection, styles, bounding box, etc.  It depends on your WMS server configuration, it's the reason we ask you to check the URL in the browser to try to see if the server is answering any error code.

**Comment by DimitrisMarm** [comment]
Hi again @DiegoGomezDeck, @mdelacalle   

first thanks for the help, it works with my ip but only if i have blue marble wms as base layer.
when i try to add any other base layer such as osm  i get this message in my device: " inconsistency in Layer's Parameters : mercator".

i use this layer : WMSLayer testLayer = new WMSLayer("buildings:test01", new URL(
                "http://10.0.22.127:8086/geoserver/buildings/wms?", false),
                WMSServerVersion.WMS_1_1_0, Sector.fromDegrees(35.330791,
                        25.28503, 35.331236, 25.285729), "image/jpeg",
                "EPSG:404000", "", true, new LevelTileCondition(0, 18),
                TimeInterval.fromDays(30), true);

and as base layer this  : final BingMapsLayer bingMapsAerial = new BingMapsLayer(
                BingMapType.Aerial(),
                "AnU5uta7s5ql_HTrRZcPLI4_zotvNefEeSxIClF1Jf7eS-mLig1jluUdCoecV7jc",
                TimeInterval.fromDays(30));
- if a set the blue marble wms as base layer i can add my wms without any problem

i have something wrong in my code or i  have problem with the projection of my wms or something else?

thanks!
