### ISSUE TITLE
camera Altidure && CameraEventHandler

### ISSUE THREAD

**Issue by DimitrisMarm** [glob3mobile/g3m#95]
Hello there,

Is there any way to get the altitude of camera when i zooming in or out?
I try to use this :
 _g3mWidget.getCameraRenderer().addHandler(new CameraEventHandler() {....}); 

 but the message where i put in it doesn't appear when i zoom or move the camera.

Thanks in advance.

**Comment by DiegoGomezDeck** [comment]
Hi @DimitrisMarm 

to get the altitude (in meter) of the camera:
  camera->getGeodeticPosition()._height

BTW, the goal of the CameraHandler subsystem is to provide a mechanism to process touch-events to move the camera.

If you need to constraint the camera position, you can use ICameraConstrainer mechanism.

If you need to make your application reacts to camera movements, use PlanetRenderer::addVisibleSectorListener() methods.

**Comment by DimitrisMarm** [comment]
Thanks @DiegoGomezDeck this was very helpful!
