### ISSUE TITLE
Drawing Lines?

### ISSUE THREAD

**Issue by stefaniea** [glob3mobile/g3m#96]
How do you draw a simple line? Having trouble figuring out which class to use.

**Comment by boyP** [comment]
Hi Stefanie, this is what I did when making two 3-D lines that share a common point at the the specified latitude and longitude. I did this in the ViewController.mm file, in the viewDidLoad method

```
G3MBuilder_iOS builder([self view]);
const Planet* planet = Planet::createEarth();
builder.setPlanet(planet);
double lat = 28.96384553643802, lon = -13.60974902228918;
CoordinateSystem sr = planet->getCoordinateSystemAt(Geodetic3D::fromDegrees(lat, lon, 0));
Mesh* _mesh = sr.createMesh(1e4, Color::red(), Color::green(), Color::yellow());
MeshRenderer* _meshrender = new MeshRenderer();
_meshrender->addMesh(_mesh);

builder.addRenderer(_meshrender);
```

Hope this helps :)

**Comment by DiegoGomezDeck** [comment]
Hello @stefaniea 

Which type of line do you need to draw?  3d-lines or lines on the ground?

**Comment by stefaniea** [comment]
3d lines given 2 points

**Comment by DiegoGomezDeck** [comment]
@stefaniea 

If you search for "GLPrimitive::lines()" all over the code, you'll find some examples.

For instance: AbstractMesh::createNormalsMesh(), Box::createMesh(const Color& color), Sphere::createWireframeMesh(const Color& color, short resolution), etc.
