### ISSUE TITLE
Pulled from purgatory and now we cannot build

### ISSUE THREAD

**Issue by boyP** [glob3mobile/g3m#97]
Hi, our branch (osm_app_poc) just pulled from purgatory recently and we are unable to build anymore. We get the error claiming we don't have a BuenosAires-Wikipedia.json file.

![screenshot 2015-04-02 17 48 52](https://cloud.githubusercontent.com/assets/6115468/6974423/977954ca-d960-11e4-9ec8-4b98a43e6331.png)

How do we resolve this issue? We have tried actually inserting an empty BuenosAires-Wikipedia.json file at the specified location but it didn't fix the issue. How do we go about resolving this issue without reverting to the previous commit.

**Comment by DiegoGomezDeck** [comment]
@boyP 

Sorry, my fault.  I pushed a version with an absolute path inside.   I just fixed on purgatory branch, please let me know if this works.

**Comment by nshoemaker** [comment]
The fix worked, but can you please give me access to commit to the repository?
